/*
 ====================================================================
  High Performance ParalleX Library (libhpx)
  
  Library initialization and cleanup function definitions
  hpx_init.h

  Copyright (c) 2013, Trustees of Indiana University 
  All rights reserved.

  This software may be modified and distributed under the terms of
  the BSD license.  See the COPYING file for details.

  This software was created at the Indiana University Center for
  Research in Extreme Scale Technologies (CREST).

  Authors:
    Patrick K. Bohan <pbohan [at] indiana.edu>
 ====================================================================
*/

#pragma once
#ifndef HPX_INIT_H_
#define HPX_INIT_H_

/**
 * @file
 * @brief Declares the global library initializer and finalizer.
 */

#include "hpx/error.h"                          /* hpx_error_t */

/**
 * The global initialization routine.
 *
 * @todo Be explicit about what errors can be generated by this call, and how
 *       the application is supposed to deal with them.
 */
hpx_error_t hpx_init(void);

/**
 * The globalal finalization routine.
 */
void hpx_cleanup(void);

#endif /* HPX_INIT_H_ */
