before_script:
 - uname -a
 - df -h
 - source scripts/check_funcs.sh

stages:
  - scan
  - check
  - cross

scan-build:
  stage: scan
  script:
  - ./bootstrap
  - scan-build ./configure --enable-shared --enable-debug --enable-instrumentation --enable-percolation --enable-agas
                --enable-hpx++ --enable-mpi --enable-photon --enable-testsuite --enable-parallel-config
                --with-photon=system --with-jemalloc=system --with-hwloc=system --with-libffi=contrib
                CFLAGS="-g -O0" CXXFLAGS="-g -O0"
  - BOUT=/tmp/scan-build-${CI_BUILD_ID}
  - scan-build -o /var/www/html/scan-builds make -j 8 | tee $BOUT
  - check_scan $BOUT

check-build:
  stage: check
  script:
  - ./bootstrap
  - ./configure --prefix=$HOME --enable-debug --enable-mpi --enable-photon --enable-testsuite
                --enable-instrumentation --enable-agas --enable-hpx++ --enable-parallel-config
                PHOTON_CARGS="--enable-debug" CFLAGS="-g -O0" CXXFLAGS="-g -O0"
  - make -j 8
  - make install
  - export HPX_THREADS=1
  - export HPX_NETWORK=isir
  - make -C tests check || check_check
  - export HPX_NETWORK=pwc
  - make -C tests check || check_check

cross-build:
  stage: cross
  script:
  - ./bootstrap
  - ./configure --enable-shared --enable-debug --enable-instrumentation --enable-percolation --enable-agas --enable-hpx++
                --enable-testsuite --enable-parallel-config --with-libffi=contrib
                --host=arm-linux-gnueabihf CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++
                CFLAGS="-g -O0" CXXFLAGS="-g -O0"
  - make -j 8
