#!/usr/bin/env bash

URL="http://stout.crest.iu.edu/hpx"
DIR="/tmp"
CONTRIB=contrib

# set the array of tarball deps here
contrib_tars=("photon-1.0.tar.bz2")
# and matching target contrib directories
contrib_dirs=("photon")

# set the command to fetch the tarballs
CMD="wget --quiet -O"
if ! type "wget" > /dev/null; then
  CMD="curl --silent -o"
fi

echo -n "Downloading and extracting contrib tarballs..."
for ((i=0; i<${#contrib_tars[@]}; i++)); do
  dir=${contrib_dirs[$i]}
  file=${contrib_tars[$i]}
  if [ ! -d ${CONTRIB}/$dir ]; then
    echo -n "$dir..."
    $CMD ${DIR}/$file ${URL}/$file
    mkdir -p ${CONTRIB}/$dir
    tar --strip-components=1 -xf ${DIR}/$file -C ${CONTRIB}/$dir
    rm -f ${DIR}/$file
  fi
done
echo "DONE"

set -e
autoreconf --force --install -I config || exit 1
rm -rf autom4te.cache
