#!/usr/bin/env bash

URL="http://stout.crest.iu.edu/hpx"
DIR=$(mktemp -d hpx.XXXXXXX --tmpdir=/tmp)
CONTRIB=contrib

# set the array of tarball deps here
contrib_tars=(photon-1.0.tar.bz2 libcuckoo-b6e84f2.tar.gz jemalloc-4.0.4.tar.bz2 libffi-e9de7e3.tar.gz)
# and matching target contrib directories
contrib_dirs=(photon libcuckoo jemalloc libffi)

# set the command to fetch the tarballs
CMD="wget --quiet -O"
if ! type "wget" > /dev/null; then
  CMD="curl --silent -o"
fi

echo -n "Downloading and extracting contrib tarballs..."
for ((i=0; i<${#contrib_tars[@]}; i++)); do
  dir=${contrib_dirs[$i]}
  file=${contrib_tars[$i]}
  if [[ ! -f ${CONTRIB}/$dir/configure ]]; then
    echo -n "$dir..."
    $CMD ${DIR}/$file ${URL}/$file
    mkdir -p ${CONTRIB}/$dir
    tar --strip-components=1 -xf ${DIR}/$file -C ${CONTRIB}/$dir
  fi
done
rm -rf ${DIR}
echo "DONE"

set -e
autoreconf --force --install -I config || exit 1
rm -rf autom4te.cache
