/* confdefs.h */
#define PACKAGE_NAME "libcuckoo"
#define PACKAGE_TARNAME "libcuckoo"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "libcuckoo 1.0"
#define PACKAGE_BUGREPORT "fawn-dev@mailman.srv.cs.cmu.edu"
#define PACKAGE_URL ""
#define PACKAGE "libcuckoo"
#define VERSION "1.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_PTHREAD 1
