/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt --input=options.ggo --func-name=hpx_option_parser --arg-struct-name=hpx_options_t --file-name=parser --default-optional --string-parser --conf-parser --no-help --no-version

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "parser.h"

const char *hpx_options_t_purpose = "";

const char *hpx_options_t_usage = "Usage: " HPX_OPTION_PARSER_PACKAGE " [OPTIONS]...";

const char *hpx_options_t_versiontext = "";

const char *hpx_options_t_description = "";

const char *hpx_options_t_help[] = {
  "HPX Runtime Options:",
  "All of the following options can either be set through the\ncommand-line using the flags given below, or through environment\nvariables of the form HPX_OPTION=value, where the option corresponds\nto the flag suffix given below.",
  "      --hpx-help                print HPX help  (default=off)",
  "      --hpx-version             print HPX version  (default=off)",
  "      --hpx-heapsize=bytes      set HPX per-PE global heap size",
  "      --hpx-gas=type            type of Global Address Space (GAS)  (possible\n                                  values=\"default\", \"smp\", \"pgas\",\n                                  \"agas\")",
  "      --hpx-boot=type           HPX bootstrap method to use  (possible\n                                  values=\"default\", \"smp\", \"mpi\",\n                                  \"pmi\")",
  "      --hpx-transport=type      type of transport to use  (possible\n                                  values=\"default\", \"mpi\", \"photon\")",
  "      --hpx-network=type        type of network to use  (possible\n                                  values=\"default\", \"smp\", \"pwc\",\n                                  \"isir\")",
  "      --hpx-statistics          print HPX runtime statistics  (default=off)",
  "      --hpx-configfile=file     HPX runtime configuration file",
  "\nScheduler Options:",
  "      --hpx-threads=threads     number of scheduler threads",
  "      --hpx-thread-affinity=policy\n                                affinitize HPX worker threads  (possible\n                                  values=\"default\", \"hwthread\", \"core\",\n                                  \"numa\", \"none\")",
  "      --hpx-stacksize=bytes     set HPX stack size",
  "      --hpx-sched-policy=policy work-stealing policy for the HPX scheduler\n                                  (possible values=\"default\", \"random\",\n                                  \"last\", \"half\", \"hybrid\")",
  "      --hpx-sched-wfthreshold=tasks\n                                bound on help-first tasks before work-first\n                                  scheduling",
  "      --hpx-sched-stackcachelimit=stacks\n                                bound on the number of stacks to cache",
  "\nLog options:",
  "      --hpx-log-at=[localities] selectively output log information",
  "      --hpx-log-level[=level,...]\n                                set the logging level  (possible\n                                  values=\"default\", \"boot\", \"sched\",\n                                  \"gas\", \"lco\", \"net\", \"trans\",\n                                  \"parcel\", \"action\", \"config\",\n                                  \"memory\", \"coll\", \"all\" default=`all')",
  "\nHPX Debug Options:",
  "      --hpx-dbg-waitat=[locality]\n                                wait for debugger at specific locality",
  "      --hpx-dbg-waitonabort     wait inside of hpx_abort()  (default=off)",
  "      --hpx-dbg-waitonsig[=sig,...]\n                                wait on program error signals  (possible\n                                  values=\"segv\", \"abrt\", \"fpe\", \"ill\",\n                                  \"bus\", \"iot\", \"sys\", \"trap\", \"all\"\n                                  default=`all')",
  "      --hpx-dbg-mprotectstacks  use mprotect() to bracket stacks to look for\n                                  stack overflows  (default=off)",
  "      --hpx-dbg-syncfree        use synchronous GAS free operations\n                                  (default=off)",
  "\nInstrumentation:",
  "      --hpx-inst-dir=dir        directory to output instrumentation files",
  "      --hpx-inst-at=[localities]\n                                set the localities to activate instrumentation\n                                  at",
  "\nTracing:",
  "      --hpx-trace-classes=class set the event classes to trace  (possible\n                                  values=\"parcel\", \"pwc\", \"sched\",\n                                  \"lco\", \"process\", \"memory\",\n                                  \"schedtimes\", \"all\")",
  "      --hpx-trace-filesize=bytes\n                                set the size of each trace file",
  "\nProfiling:",
  "      --hpx-prof-counters=counters\n                                set which PAPI counters to use for profiling\n                                  (possible values=\"HPX_L1_TCM\",\n                                  \"HPX_L2_TCM\", \"HPX_L3_TCM\",\n                                  \"HPX_TLB_TL\", \"HPX_TOT_INS\",\n                                  \"HPX_INT_INS\", \"HPX_FP_INS\",\n                                  \"HPX_LD_INS\", \"HPX_SR_INS\",\n                                  \"HPX_BR_INS\", \"HPX_TOT_CYC\", \"all\")",
  "\nISIR Network Options:",
  "      --hpx-isir-testwindow=requests\n                                number of ISIR requests to test in progress\n                                  loop",
  "      --hpx-isir-sendlimit=requests\n                                ISIR network send limit",
  "      --hpx-isir-recvlimit=requests\n                                ISIR network recv limit",
  "\nPWC Network Options:",
  "      --hpx-pwc-parcelbuffersize=bytes\n                                set the size of p2p recv buffers for parcel\n                                  sends",
  "      --hpx-pwc-parceleagerlimit=bytes\n                                set the largest eager parcel size (header\n                                  inclusive)",
  "\nPhoton Transport Options:",
  "      --hpx-photon-backend=type set the underlying network API to use\n                                  (possible values=\"default\", \"verbs\",\n                                  \"ugni\", \"fi\")",
  "      --hpx-photon-ibdev=device [verbs] set a particular IB device (also a\n                                  filter for device and port discovery, e.g.\n                                  qib0:1+mlx4_0:2)",
  "      --hpx-photon-ethdev=device\n                                [verbs] set a particular ETH device (for CMA\n                                  mode only)",
  "      --hpx-photon-ibport=integer\n                                [verbs] set a particular IB port",
  "      --hpx-photon-usecma       [verbs] enable CMA connection mode\n                                  (default=off)",
  "      --hpx-photon-ibsrq=integer\n                                [verbs] number of shared receive queues\n                                  (default 0, disabled)",
  "      --hpx-photon-btethresh=integer\n                                [ugni] set size in bytes for when BTE is used\n                                  over FMA",
  "      --hpx-photon-fiprov=provider\n                                [libfabric] provider to use (sockets, psm,\n                                  etc.)",
  "      --hpx-photon-ledgersize=integer\n                                set number of ledger entries",
  "      --hpx-photon-eagerbufsize=bytes\n                                set size of eager buffers",
  "      --hpx-photon-smallpwcsize=bytes\n                                set PWC small msg limit",
  "      --hpx-photon-maxrd=integer\n                                set max number of request descriptors",
  "      --hpx-photon-defaultrd=integer\n                                set default number of allocated descriptors",
  "      --hpx-photon-numcq=integer\n                                set number of completion queues to use (cyclic\n                                  assignment to ranks)",
  "      --hpx-photon-usercq=integer\n                                enable remote completion support (default 0,\n                                  disabled)",
  "\nOptimization:",
  "      --hpx-opt-smp[=0 off]     optimize for SMP execution",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_LONG
  , ARG_ENUM
} hpx_option_parser_arg_type;

static
void clear_given (struct hpx_options_t *args_info);
static
void clear_args (struct hpx_options_t *args_info);

static int
hpx_option_parser_internal (int argc, char **argv, struct hpx_options_t *args_info,
                        struct hpx_option_parser_params *params, const char *additional_error);

static int
hpx_option_parser_required2 (struct hpx_options_t *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


const char *hpx_option_parser_hpx_gas_values[] = {"default", "smp", "pgas", "agas", 0}; /*< Possible values for hpx-gas. */
const char *hpx_option_parser_hpx_boot_values[] = {"default", "smp", "mpi", "pmi", 0}; /*< Possible values for hpx-boot. */
const char *hpx_option_parser_hpx_transport_values[] = {"default", "mpi", "photon", 0}; /*< Possible values for hpx-transport. */
const char *hpx_option_parser_hpx_network_values[] = {"default", "smp", "pwc", "isir", 0}; /*< Possible values for hpx-network. */
const char *hpx_option_parser_hpx_thread_affinity_values[] = {"default", "hwthread", "core", "numa", "none", 0}; /*< Possible values for hpx-thread-affinity. */
const char *hpx_option_parser_hpx_sched_policy_values[] = {"default", "random", "last", "half", "hybrid", 0}; /*< Possible values for hpx-sched-policy. */
const char *hpx_option_parser_hpx_log_level_values[] = {"default", "boot", "sched", "gas", "lco", "net", "trans", "parcel", "action", "config", "memory", "coll", "all", 0}; /*< Possible values for hpx-log-level. */
const char *hpx_option_parser_hpx_dbg_waitonsig_values[] = {"segv", "abrt", "fpe", "ill", "bus", "iot", "sys", "trap", "all", 0}; /*< Possible values for hpx-dbg-waitonsig. */
const char *hpx_option_parser_hpx_trace_classes_values[] = {"parcel", "pwc", "sched", "lco", "process", "memory", "schedtimes", "all", 0}; /*< Possible values for hpx-trace-classes. */
const char *hpx_option_parser_hpx_prof_counters_values[] = {"HPX_L1_TCM", "HPX_L2_TCM", "HPX_L3_TCM", "HPX_TLB_TL", "HPX_TOT_INS", "HPX_INT_INS", "HPX_FP_INS", "HPX_LD_INS", "HPX_SR_INS", "HPX_BR_INS", "HPX_TOT_CYC", "all", 0}; /*< Possible values for hpx-prof-counters. */
const char *hpx_option_parser_hpx_photon_backend_values[] = {"default", "verbs", "ugni", "fi", 0}; /*< Possible values for hpx-photon-backend. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct hpx_options_t *args_info)
{
  args_info->hpx_help_given = 0 ;
  args_info->hpx_version_given = 0 ;
  args_info->hpx_heapsize_given = 0 ;
  args_info->hpx_gas_given = 0 ;
  args_info->hpx_boot_given = 0 ;
  args_info->hpx_transport_given = 0 ;
  args_info->hpx_network_given = 0 ;
  args_info->hpx_statistics_given = 0 ;
  args_info->hpx_configfile_given = 0 ;
  args_info->hpx_threads_given = 0 ;
  args_info->hpx_thread_affinity_given = 0 ;
  args_info->hpx_stacksize_given = 0 ;
  args_info->hpx_sched_policy_given = 0 ;
  args_info->hpx_sched_wfthreshold_given = 0 ;
  args_info->hpx_sched_stackcachelimit_given = 0 ;
  args_info->hpx_log_at_given = 0 ;
  args_info->hpx_log_level_given = 0 ;
  args_info->hpx_dbg_waitat_given = 0 ;
  args_info->hpx_dbg_waitonabort_given = 0 ;
  args_info->hpx_dbg_waitonsig_given = 0 ;
  args_info->hpx_dbg_mprotectstacks_given = 0 ;
  args_info->hpx_dbg_syncfree_given = 0 ;
  args_info->hpx_inst_dir_given = 0 ;
  args_info->hpx_inst_at_given = 0 ;
  args_info->hpx_trace_classes_given = 0 ;
  args_info->hpx_trace_filesize_given = 0 ;
  args_info->hpx_prof_counters_given = 0 ;
  args_info->hpx_isir_testwindow_given = 0 ;
  args_info->hpx_isir_sendlimit_given = 0 ;
  args_info->hpx_isir_recvlimit_given = 0 ;
  args_info->hpx_pwc_parcelbuffersize_given = 0 ;
  args_info->hpx_pwc_parceleagerlimit_given = 0 ;
  args_info->hpx_photon_backend_given = 0 ;
  args_info->hpx_photon_ibdev_given = 0 ;
  args_info->hpx_photon_ethdev_given = 0 ;
  args_info->hpx_photon_ibport_given = 0 ;
  args_info->hpx_photon_usecma_given = 0 ;
  args_info->hpx_photon_ibsrq_given = 0 ;
  args_info->hpx_photon_btethresh_given = 0 ;
  args_info->hpx_photon_fiprov_given = 0 ;
  args_info->hpx_photon_ledgersize_given = 0 ;
  args_info->hpx_photon_eagerbufsize_given = 0 ;
  args_info->hpx_photon_smallpwcsize_given = 0 ;
  args_info->hpx_photon_maxrd_given = 0 ;
  args_info->hpx_photon_defaultrd_given = 0 ;
  args_info->hpx_photon_numcq_given = 0 ;
  args_info->hpx_photon_usercq_given = 0 ;
  args_info->hpx_opt_smp_given = 0 ;
}

static
void clear_args (struct hpx_options_t *args_info)
{
  FIX_UNUSED (args_info);
  args_info->hpx_help_flag = 0;
  args_info->hpx_version_flag = 0;
  args_info->hpx_heapsize_orig = NULL;
  args_info->hpx_gas_arg = hpx_gas__NULL;
  args_info->hpx_gas_orig = NULL;
  args_info->hpx_boot_arg = hpx_boot__NULL;
  args_info->hpx_boot_orig = NULL;
  args_info->hpx_transport_arg = hpx_transport__NULL;
  args_info->hpx_transport_orig = NULL;
  args_info->hpx_network_arg = hpx_network__NULL;
  args_info->hpx_network_orig = NULL;
  args_info->hpx_statistics_flag = 0;
  args_info->hpx_configfile_arg = NULL;
  args_info->hpx_configfile_orig = NULL;
  args_info->hpx_threads_orig = NULL;
  args_info->hpx_thread_affinity_arg = hpx_thread_affinity__NULL;
  args_info->hpx_thread_affinity_orig = NULL;
  args_info->hpx_stacksize_orig = NULL;
  args_info->hpx_sched_policy_arg = hpx_sched_policy__NULL;
  args_info->hpx_sched_policy_orig = NULL;
  args_info->hpx_sched_wfthreshold_orig = NULL;
  args_info->hpx_sched_stackcachelimit_orig = NULL;
  args_info->hpx_log_at_arg = NULL;
  args_info->hpx_log_at_orig = NULL;
  args_info->hpx_log_level_arg = NULL;
  args_info->hpx_log_level_orig = NULL;
  args_info->hpx_dbg_waitat_arg = NULL;
  args_info->hpx_dbg_waitat_orig = NULL;
  args_info->hpx_dbg_waitonabort_flag = 0;
  args_info->hpx_dbg_waitonsig_arg = NULL;
  args_info->hpx_dbg_waitonsig_orig = NULL;
  args_info->hpx_dbg_mprotectstacks_flag = 0;
  args_info->hpx_dbg_syncfree_flag = 0;
  args_info->hpx_inst_dir_arg = NULL;
  args_info->hpx_inst_dir_orig = NULL;
  args_info->hpx_inst_at_arg = NULL;
  args_info->hpx_inst_at_orig = NULL;
  args_info->hpx_trace_classes_arg = NULL;
  args_info->hpx_trace_classes_orig = NULL;
  args_info->hpx_trace_filesize_orig = NULL;
  args_info->hpx_prof_counters_arg = NULL;
  args_info->hpx_prof_counters_orig = NULL;
  args_info->hpx_isir_testwindow_orig = NULL;
  args_info->hpx_isir_sendlimit_orig = NULL;
  args_info->hpx_isir_recvlimit_orig = NULL;
  args_info->hpx_pwc_parcelbuffersize_orig = NULL;
  args_info->hpx_pwc_parceleagerlimit_orig = NULL;
  args_info->hpx_photon_backend_arg = hpx_photon_backend__NULL;
  args_info->hpx_photon_backend_orig = NULL;
  args_info->hpx_photon_ibdev_arg = NULL;
  args_info->hpx_photon_ibdev_orig = NULL;
  args_info->hpx_photon_ethdev_arg = NULL;
  args_info->hpx_photon_ethdev_orig = NULL;
  args_info->hpx_photon_ibport_orig = NULL;
  args_info->hpx_photon_usecma_flag = 0;
  args_info->hpx_photon_ibsrq_orig = NULL;
  args_info->hpx_photon_btethresh_orig = NULL;
  args_info->hpx_photon_fiprov_arg = NULL;
  args_info->hpx_photon_fiprov_orig = NULL;
  args_info->hpx_photon_ledgersize_orig = NULL;
  args_info->hpx_photon_eagerbufsize_orig = NULL;
  args_info->hpx_photon_smallpwcsize_orig = NULL;
  args_info->hpx_photon_maxrd_orig = NULL;
  args_info->hpx_photon_defaultrd_orig = NULL;
  args_info->hpx_photon_numcq_orig = NULL;
  args_info->hpx_photon_usercq_orig = NULL;
  args_info->hpx_opt_smp_orig = NULL;
  
}

static
void init_args_info(struct hpx_options_t *args_info)
{


  args_info->hpx_help_help = hpx_options_t_help[2] ;
  args_info->hpx_version_help = hpx_options_t_help[3] ;
  args_info->hpx_heapsize_help = hpx_options_t_help[4] ;
  args_info->hpx_gas_help = hpx_options_t_help[5] ;
  args_info->hpx_boot_help = hpx_options_t_help[6] ;
  args_info->hpx_transport_help = hpx_options_t_help[7] ;
  args_info->hpx_network_help = hpx_options_t_help[8] ;
  args_info->hpx_statistics_help = hpx_options_t_help[9] ;
  args_info->hpx_configfile_help = hpx_options_t_help[10] ;
  args_info->hpx_threads_help = hpx_options_t_help[12] ;
  args_info->hpx_thread_affinity_help = hpx_options_t_help[13] ;
  args_info->hpx_stacksize_help = hpx_options_t_help[14] ;
  args_info->hpx_sched_policy_help = hpx_options_t_help[15] ;
  args_info->hpx_sched_wfthreshold_help = hpx_options_t_help[16] ;
  args_info->hpx_sched_stackcachelimit_help = hpx_options_t_help[17] ;
  args_info->hpx_log_at_help = hpx_options_t_help[19] ;
  args_info->hpx_log_at_min = 0;
  args_info->hpx_log_at_max = 0;
  args_info->hpx_log_level_help = hpx_options_t_help[20] ;
  args_info->hpx_log_level_min = 0;
  args_info->hpx_log_level_max = 0;
  args_info->hpx_dbg_waitat_help = hpx_options_t_help[22] ;
  args_info->hpx_dbg_waitat_min = 0;
  args_info->hpx_dbg_waitat_max = 0;
  args_info->hpx_dbg_waitonabort_help = hpx_options_t_help[23] ;
  args_info->hpx_dbg_waitonsig_help = hpx_options_t_help[24] ;
  args_info->hpx_dbg_waitonsig_min = 0;
  args_info->hpx_dbg_waitonsig_max = 0;
  args_info->hpx_dbg_mprotectstacks_help = hpx_options_t_help[25] ;
  args_info->hpx_dbg_syncfree_help = hpx_options_t_help[26] ;
  args_info->hpx_inst_dir_help = hpx_options_t_help[28] ;
  args_info->hpx_inst_at_help = hpx_options_t_help[29] ;
  args_info->hpx_inst_at_min = 0;
  args_info->hpx_inst_at_max = 0;
  args_info->hpx_trace_classes_help = hpx_options_t_help[31] ;
  args_info->hpx_trace_classes_min = 0;
  args_info->hpx_trace_classes_max = 0;
  args_info->hpx_trace_filesize_help = hpx_options_t_help[32] ;
  args_info->hpx_prof_counters_help = hpx_options_t_help[34] ;
  args_info->hpx_prof_counters_min = 0;
  args_info->hpx_prof_counters_max = 0;
  args_info->hpx_isir_testwindow_help = hpx_options_t_help[36] ;
  args_info->hpx_isir_sendlimit_help = hpx_options_t_help[37] ;
  args_info->hpx_isir_recvlimit_help = hpx_options_t_help[38] ;
  args_info->hpx_pwc_parcelbuffersize_help = hpx_options_t_help[40] ;
  args_info->hpx_pwc_parceleagerlimit_help = hpx_options_t_help[41] ;
  args_info->hpx_photon_backend_help = hpx_options_t_help[43] ;
  args_info->hpx_photon_ibdev_help = hpx_options_t_help[44] ;
  args_info->hpx_photon_ethdev_help = hpx_options_t_help[45] ;
  args_info->hpx_photon_ibport_help = hpx_options_t_help[46] ;
  args_info->hpx_photon_usecma_help = hpx_options_t_help[47] ;
  args_info->hpx_photon_ibsrq_help = hpx_options_t_help[48] ;
  args_info->hpx_photon_btethresh_help = hpx_options_t_help[49] ;
  args_info->hpx_photon_fiprov_help = hpx_options_t_help[50] ;
  args_info->hpx_photon_ledgersize_help = hpx_options_t_help[51] ;
  args_info->hpx_photon_eagerbufsize_help = hpx_options_t_help[52] ;
  args_info->hpx_photon_smallpwcsize_help = hpx_options_t_help[53] ;
  args_info->hpx_photon_maxrd_help = hpx_options_t_help[54] ;
  args_info->hpx_photon_defaultrd_help = hpx_options_t_help[55] ;
  args_info->hpx_photon_numcq_help = hpx_options_t_help[56] ;
  args_info->hpx_photon_usercq_help = hpx_options_t_help[57] ;
  args_info->hpx_opt_smp_help = hpx_options_t_help[59] ;
  
}

void
hpx_option_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(HPX_OPTION_PARSER_PACKAGE_NAME) ? HPX_OPTION_PARSER_PACKAGE_NAME : HPX_OPTION_PARSER_PACKAGE),
     HPX_OPTION_PARSER_VERSION);

  if (strlen(hpx_options_t_versiontext) > 0)
    printf("\n%s\n", hpx_options_t_versiontext);
}

static void print_help_common(void) {
  hpx_option_parser_print_version ();

  if (strlen(hpx_options_t_purpose) > 0)
    printf("\n%s\n", hpx_options_t_purpose);

  if (strlen(hpx_options_t_usage) > 0)
    printf("\n%s\n", hpx_options_t_usage);

  printf("\n");

  if (strlen(hpx_options_t_description) > 0)
    printf("%s\n\n", hpx_options_t_description);
}

void
hpx_option_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (hpx_options_t_help[i])
    printf("%s\n", hpx_options_t_help[i++]);
}

void
hpx_option_parser_init (struct hpx_options_t *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
hpx_option_parser_params_init(struct hpx_option_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct hpx_option_parser_params *
hpx_option_parser_params_create(void)
{
  struct hpx_option_parser_params *params = 
    (struct hpx_option_parser_params *)malloc(sizeof(struct hpx_option_parser_params));
  hpx_option_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    long long_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}

/**
 * The passed arg parameter is NOT set to 0 from this function
 */
static void
free_multiple_field(unsigned int len, void *arg, char ***orig)
{
  unsigned int i;
  if (arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (arg);
    free (*orig);
    *orig = 0;
  }
}


static void
hpx_option_parser_release (struct hpx_options_t *args_info)
{

  free_string_field (&(args_info->hpx_heapsize_orig));
  free_string_field (&(args_info->hpx_gas_orig));
  free_string_field (&(args_info->hpx_boot_orig));
  free_string_field (&(args_info->hpx_transport_orig));
  free_string_field (&(args_info->hpx_network_orig));
  free_string_field (&(args_info->hpx_configfile_arg));
  free_string_field (&(args_info->hpx_configfile_orig));
  free_string_field (&(args_info->hpx_threads_orig));
  free_string_field (&(args_info->hpx_thread_affinity_orig));
  free_string_field (&(args_info->hpx_stacksize_orig));
  free_string_field (&(args_info->hpx_sched_policy_orig));
  free_string_field (&(args_info->hpx_sched_wfthreshold_orig));
  free_string_field (&(args_info->hpx_sched_stackcachelimit_orig));
  free_multiple_field (args_info->hpx_log_at_given, (void *)(args_info->hpx_log_at_arg), &(args_info->hpx_log_at_orig));
  args_info->hpx_log_at_arg = 0;
  free_multiple_field (args_info->hpx_log_level_given, (void *)(args_info->hpx_log_level_arg), &(args_info->hpx_log_level_orig));
  args_info->hpx_log_level_arg = 0;
  free_multiple_field (args_info->hpx_dbg_waitat_given, (void *)(args_info->hpx_dbg_waitat_arg), &(args_info->hpx_dbg_waitat_orig));
  args_info->hpx_dbg_waitat_arg = 0;
  free_multiple_field (args_info->hpx_dbg_waitonsig_given, (void *)(args_info->hpx_dbg_waitonsig_arg), &(args_info->hpx_dbg_waitonsig_orig));
  args_info->hpx_dbg_waitonsig_arg = 0;
  free_string_field (&(args_info->hpx_inst_dir_arg));
  free_string_field (&(args_info->hpx_inst_dir_orig));
  free_multiple_field (args_info->hpx_inst_at_given, (void *)(args_info->hpx_inst_at_arg), &(args_info->hpx_inst_at_orig));
  args_info->hpx_inst_at_arg = 0;
  free_multiple_field (args_info->hpx_trace_classes_given, (void *)(args_info->hpx_trace_classes_arg), &(args_info->hpx_trace_classes_orig));
  args_info->hpx_trace_classes_arg = 0;
  free_string_field (&(args_info->hpx_trace_filesize_orig));
  free_multiple_field (args_info->hpx_prof_counters_given, (void *)(args_info->hpx_prof_counters_arg), &(args_info->hpx_prof_counters_orig));
  args_info->hpx_prof_counters_arg = 0;
  free_string_field (&(args_info->hpx_isir_testwindow_orig));
  free_string_field (&(args_info->hpx_isir_sendlimit_orig));
  free_string_field (&(args_info->hpx_isir_recvlimit_orig));
  free_string_field (&(args_info->hpx_pwc_parcelbuffersize_orig));
  free_string_field (&(args_info->hpx_pwc_parceleagerlimit_orig));
  free_string_field (&(args_info->hpx_photon_backend_orig));
  free_string_field (&(args_info->hpx_photon_ibdev_arg));
  free_string_field (&(args_info->hpx_photon_ibdev_orig));
  free_string_field (&(args_info->hpx_photon_ethdev_arg));
  free_string_field (&(args_info->hpx_photon_ethdev_orig));
  free_string_field (&(args_info->hpx_photon_ibport_orig));
  free_string_field (&(args_info->hpx_photon_ibsrq_orig));
  free_string_field (&(args_info->hpx_photon_btethresh_orig));
  free_string_field (&(args_info->hpx_photon_fiprov_arg));
  free_string_field (&(args_info->hpx_photon_fiprov_orig));
  free_string_field (&(args_info->hpx_photon_ledgersize_orig));
  free_string_field (&(args_info->hpx_photon_eagerbufsize_orig));
  free_string_field (&(args_info->hpx_photon_smallpwcsize_orig));
  free_string_field (&(args_info->hpx_photon_maxrd_orig));
  free_string_field (&(args_info->hpx_photon_defaultrd_orig));
  free_string_field (&(args_info->hpx_photon_numcq_orig));
  free_string_field (&(args_info->hpx_photon_usercq_orig));
  free_string_field (&(args_info->hpx_opt_smp_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
hpx_option_parser_dump(FILE *outfile, struct hpx_options_t *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", HPX_OPTION_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->hpx_help_given)
    write_into_file(outfile, "hpx-help", 0, 0 );
  if (args_info->hpx_version_given)
    write_into_file(outfile, "hpx-version", 0, 0 );
  if (args_info->hpx_heapsize_given)
    write_into_file(outfile, "hpx-heapsize", args_info->hpx_heapsize_orig, 0);
  if (args_info->hpx_gas_given)
    write_into_file(outfile, "hpx-gas", args_info->hpx_gas_orig, hpx_option_parser_hpx_gas_values);
  if (args_info->hpx_boot_given)
    write_into_file(outfile, "hpx-boot", args_info->hpx_boot_orig, hpx_option_parser_hpx_boot_values);
  if (args_info->hpx_transport_given)
    write_into_file(outfile, "hpx-transport", args_info->hpx_transport_orig, hpx_option_parser_hpx_transport_values);
  if (args_info->hpx_network_given)
    write_into_file(outfile, "hpx-network", args_info->hpx_network_orig, hpx_option_parser_hpx_network_values);
  if (args_info->hpx_statistics_given)
    write_into_file(outfile, "hpx-statistics", 0, 0 );
  if (args_info->hpx_configfile_given)
    write_into_file(outfile, "hpx-configfile", args_info->hpx_configfile_orig, 0);
  if (args_info->hpx_threads_given)
    write_into_file(outfile, "hpx-threads", args_info->hpx_threads_orig, 0);
  if (args_info->hpx_thread_affinity_given)
    write_into_file(outfile, "hpx-thread-affinity", args_info->hpx_thread_affinity_orig, hpx_option_parser_hpx_thread_affinity_values);
  if (args_info->hpx_stacksize_given)
    write_into_file(outfile, "hpx-stacksize", args_info->hpx_stacksize_orig, 0);
  if (args_info->hpx_sched_policy_given)
    write_into_file(outfile, "hpx-sched-policy", args_info->hpx_sched_policy_orig, hpx_option_parser_hpx_sched_policy_values);
  if (args_info->hpx_sched_wfthreshold_given)
    write_into_file(outfile, "hpx-sched-wfthreshold", args_info->hpx_sched_wfthreshold_orig, 0);
  if (args_info->hpx_sched_stackcachelimit_given)
    write_into_file(outfile, "hpx-sched-stackcachelimit", args_info->hpx_sched_stackcachelimit_orig, 0);
  write_multiple_into_file(outfile, args_info->hpx_log_at_given, "hpx-log-at", args_info->hpx_log_at_orig, 0);
  write_multiple_into_file(outfile, args_info->hpx_log_level_given, "hpx-log-level", args_info->hpx_log_level_orig, hpx_option_parser_hpx_log_level_values);
  write_multiple_into_file(outfile, args_info->hpx_dbg_waitat_given, "hpx-dbg-waitat", args_info->hpx_dbg_waitat_orig, 0);
  if (args_info->hpx_dbg_waitonabort_given)
    write_into_file(outfile, "hpx-dbg-waitonabort", 0, 0 );
  write_multiple_into_file(outfile, args_info->hpx_dbg_waitonsig_given, "hpx-dbg-waitonsig", args_info->hpx_dbg_waitonsig_orig, hpx_option_parser_hpx_dbg_waitonsig_values);
  if (args_info->hpx_dbg_mprotectstacks_given)
    write_into_file(outfile, "hpx-dbg-mprotectstacks", 0, 0 );
  if (args_info->hpx_dbg_syncfree_given)
    write_into_file(outfile, "hpx-dbg-syncfree", 0, 0 );
  if (args_info->hpx_inst_dir_given)
    write_into_file(outfile, "hpx-inst-dir", args_info->hpx_inst_dir_orig, 0);
  write_multiple_into_file(outfile, args_info->hpx_inst_at_given, "hpx-inst-at", args_info->hpx_inst_at_orig, 0);
  write_multiple_into_file(outfile, args_info->hpx_trace_classes_given, "hpx-trace-classes", args_info->hpx_trace_classes_orig, hpx_option_parser_hpx_trace_classes_values);
  if (args_info->hpx_trace_filesize_given)
    write_into_file(outfile, "hpx-trace-filesize", args_info->hpx_trace_filesize_orig, 0);
  write_multiple_into_file(outfile, args_info->hpx_prof_counters_given, "hpx-prof-counters", args_info->hpx_prof_counters_orig, hpx_option_parser_hpx_prof_counters_values);
  if (args_info->hpx_isir_testwindow_given)
    write_into_file(outfile, "hpx-isir-testwindow", args_info->hpx_isir_testwindow_orig, 0);
  if (args_info->hpx_isir_sendlimit_given)
    write_into_file(outfile, "hpx-isir-sendlimit", args_info->hpx_isir_sendlimit_orig, 0);
  if (args_info->hpx_isir_recvlimit_given)
    write_into_file(outfile, "hpx-isir-recvlimit", args_info->hpx_isir_recvlimit_orig, 0);
  if (args_info->hpx_pwc_parcelbuffersize_given)
    write_into_file(outfile, "hpx-pwc-parcelbuffersize", args_info->hpx_pwc_parcelbuffersize_orig, 0);
  if (args_info->hpx_pwc_parceleagerlimit_given)
    write_into_file(outfile, "hpx-pwc-parceleagerlimit", args_info->hpx_pwc_parceleagerlimit_orig, 0);
  if (args_info->hpx_photon_backend_given)
    write_into_file(outfile, "hpx-photon-backend", args_info->hpx_photon_backend_orig, hpx_option_parser_hpx_photon_backend_values);
  if (args_info->hpx_photon_ibdev_given)
    write_into_file(outfile, "hpx-photon-ibdev", args_info->hpx_photon_ibdev_orig, 0);
  if (args_info->hpx_photon_ethdev_given)
    write_into_file(outfile, "hpx-photon-ethdev", args_info->hpx_photon_ethdev_orig, 0);
  if (args_info->hpx_photon_ibport_given)
    write_into_file(outfile, "hpx-photon-ibport", args_info->hpx_photon_ibport_orig, 0);
  if (args_info->hpx_photon_usecma_given)
    write_into_file(outfile, "hpx-photon-usecma", 0, 0 );
  if (args_info->hpx_photon_ibsrq_given)
    write_into_file(outfile, "hpx-photon-ibsrq", args_info->hpx_photon_ibsrq_orig, 0);
  if (args_info->hpx_photon_btethresh_given)
    write_into_file(outfile, "hpx-photon-btethresh", args_info->hpx_photon_btethresh_orig, 0);
  if (args_info->hpx_photon_fiprov_given)
    write_into_file(outfile, "hpx-photon-fiprov", args_info->hpx_photon_fiprov_orig, 0);
  if (args_info->hpx_photon_ledgersize_given)
    write_into_file(outfile, "hpx-photon-ledgersize", args_info->hpx_photon_ledgersize_orig, 0);
  if (args_info->hpx_photon_eagerbufsize_given)
    write_into_file(outfile, "hpx-photon-eagerbufsize", args_info->hpx_photon_eagerbufsize_orig, 0);
  if (args_info->hpx_photon_smallpwcsize_given)
    write_into_file(outfile, "hpx-photon-smallpwcsize", args_info->hpx_photon_smallpwcsize_orig, 0);
  if (args_info->hpx_photon_maxrd_given)
    write_into_file(outfile, "hpx-photon-maxrd", args_info->hpx_photon_maxrd_orig, 0);
  if (args_info->hpx_photon_defaultrd_given)
    write_into_file(outfile, "hpx-photon-defaultrd", args_info->hpx_photon_defaultrd_orig, 0);
  if (args_info->hpx_photon_numcq_given)
    write_into_file(outfile, "hpx-photon-numcq", args_info->hpx_photon_numcq_orig, 0);
  if (args_info->hpx_photon_usercq_given)
    write_into_file(outfile, "hpx-photon-usercq", args_info->hpx_photon_usercq_orig, 0);
  if (args_info->hpx_opt_smp_given)
    write_into_file(outfile, "hpx-opt-smp", args_info->hpx_opt_smp_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
hpx_option_parser_file_save(const char *filename, struct hpx_options_t *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", HPX_OPTION_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = hpx_option_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
hpx_option_parser_free (struct hpx_options_t *args_info)
{
  hpx_option_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
hpx_option_parser (int argc, char **argv, struct hpx_options_t *args_info)
{
  return hpx_option_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
hpx_option_parser_ext (int argc, char **argv, struct hpx_options_t *args_info,
                   struct hpx_option_parser_params *params)
{
  int result;
  result = hpx_option_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
hpx_option_parser2 (int argc, char **argv, struct hpx_options_t *args_info, int override, int initialize, int check_required)
{
  int result;
  struct hpx_option_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = hpx_option_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
hpx_option_parser_required (struct hpx_options_t *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (hpx_option_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
hpx_option_parser_required2 (struct hpx_options_t *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_log_at_given, args_info->hpx_log_at_min, args_info->hpx_log_at_max, "'--hpx-log-at'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_log_level_given, args_info->hpx_log_level_min, args_info->hpx_log_level_max, "'--hpx-log-level'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_dbg_waitat_given, args_info->hpx_dbg_waitat_min, args_info->hpx_dbg_waitat_max, "'--hpx-dbg-waitat'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_dbg_waitonsig_given, args_info->hpx_dbg_waitonsig_min, args_info->hpx_dbg_waitonsig_max, "'--hpx-dbg-waitonsig'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_inst_at_given, args_info->hpx_inst_at_min, args_info->hpx_inst_at_max, "'--hpx-inst-at'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_trace_classes_given, args_info->hpx_trace_classes_min, args_info->hpx_trace_classes_max, "'--hpx-trace-classes'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_prof_counters_given, args_info->hpx_prof_counters_min, args_info->hpx_prof_counters_max, "'--hpx-prof-counters'"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see hpx_option_parser_params.check_ambiguity
 * @param override @see hpx_option_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               hpx_option_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_LONG:
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_LONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               hpx_option_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               hpx_option_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
    case ARG_ENUM:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_LONG:
      *((long **)field) = (long *)realloc (*((long **)field), (field_given + prev_given) * sizeof (long)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_LONG:
          (*((long **)field))[i + field_given] = tmp->arg.long_arg; break;
        case ARG_ENUM:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
      case ARG_ENUM:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_LONG:
        if (! *((long **)field)) {
          *((long **)field) = (long *)malloc (sizeof (long));
          (*((long **)field))[0] = default_value->long_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
hpx_option_parser_internal (
  int argc, char **argv, struct hpx_options_t *args_info,
                        struct hpx_option_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  union generic_value multiple_default_value;

  struct generic_list * hpx_log_at_list = NULL;
  struct generic_list * hpx_log_level_list = NULL;
  struct generic_list * hpx_dbg_waitat_list = NULL;
  struct generic_list * hpx_dbg_waitonsig_list = NULL;
  struct generic_list * hpx_inst_at_list = NULL;
  struct generic_list * hpx_trace_classes_list = NULL;
  struct generic_list * hpx_prof_counters_list = NULL;
  int error_occurred = 0;
  struct hpx_options_t local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    hpx_option_parser_init (args_info);

  hpx_option_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "hpx-help",	0, NULL, 0 },
        { "hpx-version",	0, NULL, 0 },
        { "hpx-heapsize",	1, NULL, 0 },
        { "hpx-gas",	1, NULL, 0 },
        { "hpx-boot",	1, NULL, 0 },
        { "hpx-transport",	1, NULL, 0 },
        { "hpx-network",	1, NULL, 0 },
        { "hpx-statistics",	0, NULL, 0 },
        { "hpx-configfile",	1, NULL, 0 },
        { "hpx-threads",	1, NULL, 0 },
        { "hpx-thread-affinity",	1, NULL, 0 },
        { "hpx-stacksize",	1, NULL, 0 },
        { "hpx-sched-policy",	1, NULL, 0 },
        { "hpx-sched-wfthreshold",	1, NULL, 0 },
        { "hpx-sched-stackcachelimit",	1, NULL, 0 },
        { "hpx-log-at",	1, NULL, 0 },
        { "hpx-log-level",	2, NULL, 0 },
        { "hpx-dbg-waitat",	1, NULL, 0 },
        { "hpx-dbg-waitonabort",	0, NULL, 0 },
        { "hpx-dbg-waitonsig",	2, NULL, 0 },
        { "hpx-dbg-mprotectstacks",	0, NULL, 0 },
        { "hpx-dbg-syncfree",	0, NULL, 0 },
        { "hpx-inst-dir",	1, NULL, 0 },
        { "hpx-inst-at",	1, NULL, 0 },
        { "hpx-trace-classes",	1, NULL, 0 },
        { "hpx-trace-filesize",	1, NULL, 0 },
        { "hpx-prof-counters",	1, NULL, 0 },
        { "hpx-isir-testwindow",	1, NULL, 0 },
        { "hpx-isir-sendlimit",	1, NULL, 0 },
        { "hpx-isir-recvlimit",	1, NULL, 0 },
        { "hpx-pwc-parcelbuffersize",	1, NULL, 0 },
        { "hpx-pwc-parceleagerlimit",	1, NULL, 0 },
        { "hpx-photon-backend",	1, NULL, 0 },
        { "hpx-photon-ibdev",	1, NULL, 0 },
        { "hpx-photon-ethdev",	1, NULL, 0 },
        { "hpx-photon-ibport",	1, NULL, 0 },
        { "hpx-photon-usecma",	0, NULL, 0 },
        { "hpx-photon-ibsrq",	1, NULL, 0 },
        { "hpx-photon-btethresh",	1, NULL, 0 },
        { "hpx-photon-fiprov",	1, NULL, 0 },
        { "hpx-photon-ledgersize",	1, NULL, 0 },
        { "hpx-photon-eagerbufsize",	1, NULL, 0 },
        { "hpx-photon-smallpwcsize",	1, NULL, 0 },
        { "hpx-photon-maxrd",	1, NULL, 0 },
        { "hpx-photon-defaultrd",	1, NULL, 0 },
        { "hpx-photon-numcq",	1, NULL, 0 },
        { "hpx-photon-usercq",	1, NULL, 0 },
        { "hpx-opt-smp",	2, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {

        case 0:	/* Long option with no short option */
          /* print HPX help.  */
          if (strcmp (long_options[option_index].name, "hpx-help") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_help_flag), 0, &(args_info->hpx_help_given),
                &(local_args_info.hpx_help_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-help", '-',
                additional_error))
              goto failure;
          
          }
          /* print HPX version.  */
          else if (strcmp (long_options[option_index].name, "hpx-version") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_version_flag), 0, &(args_info->hpx_version_given),
                &(local_args_info.hpx_version_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-version", '-',
                additional_error))
              goto failure;
          
          }
          /* set HPX per-PE global heap size.  */
          else if (strcmp (long_options[option_index].name, "hpx-heapsize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_heapsize_arg), 
                 &(args_info->hpx_heapsize_orig), &(args_info->hpx_heapsize_given),
                &(local_args_info.hpx_heapsize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-heapsize", '-',
                additional_error))
              goto failure;
          
          }
          /* type of Global Address Space (GAS).  */
          else if (strcmp (long_options[option_index].name, "hpx-gas") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_gas_arg), 
                 &(args_info->hpx_gas_orig), &(args_info->hpx_gas_given),
                &(local_args_info.hpx_gas_given), optarg, hpx_option_parser_hpx_gas_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-gas", '-',
                additional_error))
              goto failure;
          
          }
          /* HPX bootstrap method to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-boot") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_boot_arg), 
                 &(args_info->hpx_boot_orig), &(args_info->hpx_boot_given),
                &(local_args_info.hpx_boot_given), optarg, hpx_option_parser_hpx_boot_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-boot", '-',
                additional_error))
              goto failure;
          
          }
          /* type of transport to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-transport") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_transport_arg), 
                 &(args_info->hpx_transport_orig), &(args_info->hpx_transport_given),
                &(local_args_info.hpx_transport_given), optarg, hpx_option_parser_hpx_transport_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-transport", '-',
                additional_error))
              goto failure;
          
          }
          /* type of network to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-network") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_network_arg), 
                 &(args_info->hpx_network_orig), &(args_info->hpx_network_given),
                &(local_args_info.hpx_network_given), optarg, hpx_option_parser_hpx_network_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-network", '-',
                additional_error))
              goto failure;
          
          }
          /* print HPX runtime statistics.  */
          else if (strcmp (long_options[option_index].name, "hpx-statistics") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_statistics_flag), 0, &(args_info->hpx_statistics_given),
                &(local_args_info.hpx_statistics_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-statistics", '-',
                additional_error))
              goto failure;
          
          }
          /* HPX runtime configuration file.  */
          else if (strcmp (long_options[option_index].name, "hpx-configfile") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_configfile_arg), 
                 &(args_info->hpx_configfile_orig), &(args_info->hpx_configfile_given),
                &(local_args_info.hpx_configfile_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hpx-configfile", '-',
                additional_error))
              goto failure;
          
          }
          /* number of scheduler threads.  */
          else if (strcmp (long_options[option_index].name, "hpx-threads") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_threads_arg), 
                 &(args_info->hpx_threads_orig), &(args_info->hpx_threads_given),
                &(local_args_info.hpx_threads_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-threads", '-',
                additional_error))
              goto failure;
          
          }
          /* affinitize HPX worker threads.  */
          else if (strcmp (long_options[option_index].name, "hpx-thread-affinity") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_thread_affinity_arg), 
                 &(args_info->hpx_thread_affinity_orig), &(args_info->hpx_thread_affinity_given),
                &(local_args_info.hpx_thread_affinity_given), optarg, hpx_option_parser_hpx_thread_affinity_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-thread-affinity", '-',
                additional_error))
              goto failure;
          
          }
          /* set HPX stack size.  */
          else if (strcmp (long_options[option_index].name, "hpx-stacksize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_stacksize_arg), 
                 &(args_info->hpx_stacksize_orig), &(args_info->hpx_stacksize_given),
                &(local_args_info.hpx_stacksize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-stacksize", '-',
                additional_error))
              goto failure;
          
          }
          /* work-stealing policy for the HPX scheduler.  */
          else if (strcmp (long_options[option_index].name, "hpx-sched-policy") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_sched_policy_arg), 
                 &(args_info->hpx_sched_policy_orig), &(args_info->hpx_sched_policy_given),
                &(local_args_info.hpx_sched_policy_given), optarg, hpx_option_parser_hpx_sched_policy_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-sched-policy", '-',
                additional_error))
              goto failure;
          
          }
          /* bound on help-first tasks before work-first scheduling.  */
          else if (strcmp (long_options[option_index].name, "hpx-sched-wfthreshold") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_sched_wfthreshold_arg), 
                 &(args_info->hpx_sched_wfthreshold_orig), &(args_info->hpx_sched_wfthreshold_given),
                &(local_args_info.hpx_sched_wfthreshold_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-sched-wfthreshold", '-',
                additional_error))
              goto failure;
          
          }
          /* bound on the number of stacks to cache.  */
          else if (strcmp (long_options[option_index].name, "hpx-sched-stackcachelimit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_sched_stackcachelimit_arg), 
                 &(args_info->hpx_sched_stackcachelimit_orig), &(args_info->hpx_sched_stackcachelimit_given),
                &(local_args_info.hpx_sched_stackcachelimit_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-sched-stackcachelimit", '-',
                additional_error))
              goto failure;
          
          }
          /* selectively output log information.  */
          else if (strcmp (long_options[option_index].name, "hpx-log-at") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_log_at_list, 
                &(local_args_info.hpx_log_at_given), optarg, 0, 0, ARG_INT,
                "hpx-log-at", '-',
                additional_error))
              goto failure;
          
          }
          /* set the logging level.  */
          else if (strcmp (long_options[option_index].name, "hpx-log-level") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_log_level_list, 
                &(local_args_info.hpx_log_level_given), optarg, hpx_option_parser_hpx_log_level_values, "all", ARG_ENUM,
                "hpx-log-level", '-',
                additional_error))
              goto failure;
          
          }
          /* wait for debugger at specific locality.  */
          else if (strcmp (long_options[option_index].name, "hpx-dbg-waitat") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_dbg_waitat_list, 
                &(local_args_info.hpx_dbg_waitat_given), optarg, 0, 0, ARG_INT,
                "hpx-dbg-waitat", '-',
                additional_error))
              goto failure;
          
          }
          /* wait inside of hpx_abort().  */
          else if (strcmp (long_options[option_index].name, "hpx-dbg-waitonabort") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_dbg_waitonabort_flag), 0, &(args_info->hpx_dbg_waitonabort_given),
                &(local_args_info.hpx_dbg_waitonabort_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-dbg-waitonabort", '-',
                additional_error))
              goto failure;
          
          }
          /* wait on program error signals.  */
          else if (strcmp (long_options[option_index].name, "hpx-dbg-waitonsig") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_dbg_waitonsig_list, 
                &(local_args_info.hpx_dbg_waitonsig_given), optarg, hpx_option_parser_hpx_dbg_waitonsig_values, "all", ARG_ENUM,
                "hpx-dbg-waitonsig", '-',
                additional_error))
              goto failure;
          
          }
          /* use mprotect() to bracket stacks to look for stack overflows.  */
          else if (strcmp (long_options[option_index].name, "hpx-dbg-mprotectstacks") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_dbg_mprotectstacks_flag), 0, &(args_info->hpx_dbg_mprotectstacks_given),
                &(local_args_info.hpx_dbg_mprotectstacks_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-dbg-mprotectstacks", '-',
                additional_error))
              goto failure;
          
          }
          /* use synchronous GAS free operations.  */
          else if (strcmp (long_options[option_index].name, "hpx-dbg-syncfree") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_dbg_syncfree_flag), 0, &(args_info->hpx_dbg_syncfree_given),
                &(local_args_info.hpx_dbg_syncfree_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-dbg-syncfree", '-',
                additional_error))
              goto failure;
          
          }
          /* directory to output instrumentation files.  */
          else if (strcmp (long_options[option_index].name, "hpx-inst-dir") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_inst_dir_arg), 
                 &(args_info->hpx_inst_dir_orig), &(args_info->hpx_inst_dir_given),
                &(local_args_info.hpx_inst_dir_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hpx-inst-dir", '-',
                additional_error))
              goto failure;
          
          }
          /* set the localities to activate instrumentation at.  */
          else if (strcmp (long_options[option_index].name, "hpx-inst-at") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_inst_at_list, 
                &(local_args_info.hpx_inst_at_given), optarg, 0, 0, ARG_INT,
                "hpx-inst-at", '-',
                additional_error))
              goto failure;
          
          }
          /* set the event classes to trace.  */
          else if (strcmp (long_options[option_index].name, "hpx-trace-classes") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_trace_classes_list, 
                &(local_args_info.hpx_trace_classes_given), optarg, hpx_option_parser_hpx_trace_classes_values, 0, ARG_ENUM,
                "hpx-trace-classes", '-',
                additional_error))
              goto failure;
          
          }
          /* set the size of each trace file.  */
          else if (strcmp (long_options[option_index].name, "hpx-trace-filesize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_trace_filesize_arg), 
                 &(args_info->hpx_trace_filesize_orig), &(args_info->hpx_trace_filesize_given),
                &(local_args_info.hpx_trace_filesize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-trace-filesize", '-',
                additional_error))
              goto failure;
          
          }
          /* set which PAPI counters to use for profiling.  */
          else if (strcmp (long_options[option_index].name, "hpx-prof-counters") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_prof_counters_list, 
                &(local_args_info.hpx_prof_counters_given), optarg, hpx_option_parser_hpx_prof_counters_values, 0, ARG_ENUM,
                "hpx-prof-counters", '-',
                additional_error))
              goto failure;
          
          }
          /* number of ISIR requests to test in progress loop.  */
          else if (strcmp (long_options[option_index].name, "hpx-isir-testwindow") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_isir_testwindow_arg), 
                 &(args_info->hpx_isir_testwindow_orig), &(args_info->hpx_isir_testwindow_given),
                &(local_args_info.hpx_isir_testwindow_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-isir-testwindow", '-',
                additional_error))
              goto failure;
          
          }
          /* ISIR network send limit.  */
          else if (strcmp (long_options[option_index].name, "hpx-isir-sendlimit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_isir_sendlimit_arg), 
                 &(args_info->hpx_isir_sendlimit_orig), &(args_info->hpx_isir_sendlimit_given),
                &(local_args_info.hpx_isir_sendlimit_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-isir-sendlimit", '-',
                additional_error))
              goto failure;
          
          }
          /* ISIR network recv limit.  */
          else if (strcmp (long_options[option_index].name, "hpx-isir-recvlimit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_isir_recvlimit_arg), 
                 &(args_info->hpx_isir_recvlimit_orig), &(args_info->hpx_isir_recvlimit_given),
                &(local_args_info.hpx_isir_recvlimit_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-isir-recvlimit", '-',
                additional_error))
              goto failure;
          
          }
          /* set the size of p2p recv buffers for parcel sends.  */
          else if (strcmp (long_options[option_index].name, "hpx-pwc-parcelbuffersize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_pwc_parcelbuffersize_arg), 
                 &(args_info->hpx_pwc_parcelbuffersize_orig), &(args_info->hpx_pwc_parcelbuffersize_given),
                &(local_args_info.hpx_pwc_parcelbuffersize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-pwc-parcelbuffersize", '-',
                additional_error))
              goto failure;
          
          }
          /* set the largest eager parcel size (header inclusive).  */
          else if (strcmp (long_options[option_index].name, "hpx-pwc-parceleagerlimit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_pwc_parceleagerlimit_arg), 
                 &(args_info->hpx_pwc_parceleagerlimit_orig), &(args_info->hpx_pwc_parceleagerlimit_given),
                &(local_args_info.hpx_pwc_parceleagerlimit_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-pwc-parceleagerlimit", '-',
                additional_error))
              goto failure;
          
          }
          /* set the underlying network API to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-backend") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_backend_arg), 
                 &(args_info->hpx_photon_backend_orig), &(args_info->hpx_photon_backend_given),
                &(local_args_info.hpx_photon_backend_given), optarg, hpx_option_parser_hpx_photon_backend_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-photon-backend", '-',
                additional_error))
              goto failure;
          
          }
          /* [verbs] set a particular IB device (also a filter for device and port discovery, e.g. qib0:1+mlx4_0:2).  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-ibdev") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_ibdev_arg), 
                 &(args_info->hpx_photon_ibdev_orig), &(args_info->hpx_photon_ibdev_given),
                &(local_args_info.hpx_photon_ibdev_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hpx-photon-ibdev", '-',
                additional_error))
              goto failure;
          
          }
          /* [verbs] set a particular ETH device (for CMA mode only).  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-ethdev") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_ethdev_arg), 
                 &(args_info->hpx_photon_ethdev_orig), &(args_info->hpx_photon_ethdev_given),
                &(local_args_info.hpx_photon_ethdev_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hpx-photon-ethdev", '-',
                additional_error))
              goto failure;
          
          }
          /* [verbs] set a particular IB port.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-ibport") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_ibport_arg), 
                 &(args_info->hpx_photon_ibport_orig), &(args_info->hpx_photon_ibport_given),
                &(local_args_info.hpx_photon_ibport_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-ibport", '-',
                additional_error))
              goto failure;
          
          }
          /* [verbs] enable CMA connection mode.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-usecma") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_photon_usecma_flag), 0, &(args_info->hpx_photon_usecma_given),
                &(local_args_info.hpx_photon_usecma_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-photon-usecma", '-',
                additional_error))
              goto failure;
          
          }
          /* [verbs] number of shared receive queues (default 0, disabled).  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-ibsrq") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_ibsrq_arg), 
                 &(args_info->hpx_photon_ibsrq_orig), &(args_info->hpx_photon_ibsrq_given),
                &(local_args_info.hpx_photon_ibsrq_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-ibsrq", '-',
                additional_error))
              goto failure;
          
          }
          /* [ugni] set size in bytes for when BTE is used over FMA.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-btethresh") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_btethresh_arg), 
                 &(args_info->hpx_photon_btethresh_orig), &(args_info->hpx_photon_btethresh_given),
                &(local_args_info.hpx_photon_btethresh_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-btethresh", '-',
                additional_error))
              goto failure;
          
          }
          /* [libfabric] provider to use (sockets, psm, etc.).  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-fiprov") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_fiprov_arg), 
                 &(args_info->hpx_photon_fiprov_orig), &(args_info->hpx_photon_fiprov_given),
                &(local_args_info.hpx_photon_fiprov_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hpx-photon-fiprov", '-',
                additional_error))
              goto failure;
          
          }
          /* set number of ledger entries.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-ledgersize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_ledgersize_arg), 
                 &(args_info->hpx_photon_ledgersize_orig), &(args_info->hpx_photon_ledgersize_given),
                &(local_args_info.hpx_photon_ledgersize_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-ledgersize", '-',
                additional_error))
              goto failure;
          
          }
          /* set size of eager buffers.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-eagerbufsize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_eagerbufsize_arg), 
                 &(args_info->hpx_photon_eagerbufsize_orig), &(args_info->hpx_photon_eagerbufsize_given),
                &(local_args_info.hpx_photon_eagerbufsize_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-eagerbufsize", '-',
                additional_error))
              goto failure;
          
          }
          /* set PWC small msg limit.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-smallpwcsize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_smallpwcsize_arg), 
                 &(args_info->hpx_photon_smallpwcsize_orig), &(args_info->hpx_photon_smallpwcsize_given),
                &(local_args_info.hpx_photon_smallpwcsize_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-smallpwcsize", '-',
                additional_error))
              goto failure;
          
          }
          /* set max number of request descriptors.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-maxrd") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_maxrd_arg), 
                 &(args_info->hpx_photon_maxrd_orig), &(args_info->hpx_photon_maxrd_given),
                &(local_args_info.hpx_photon_maxrd_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-maxrd", '-',
                additional_error))
              goto failure;
          
          }
          /* set default number of allocated descriptors.  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-defaultrd") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_defaultrd_arg), 
                 &(args_info->hpx_photon_defaultrd_orig), &(args_info->hpx_photon_defaultrd_given),
                &(local_args_info.hpx_photon_defaultrd_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-defaultrd", '-',
                additional_error))
              goto failure;
          
          }
          /* set number of completion queues to use (cyclic assignment to ranks).  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-numcq") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_numcq_arg), 
                 &(args_info->hpx_photon_numcq_orig), &(args_info->hpx_photon_numcq_given),
                &(local_args_info.hpx_photon_numcq_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-numcq", '-',
                additional_error))
              goto failure;
          
          }
          /* enable remote completion support (default 0, disabled).  */
          else if (strcmp (long_options[option_index].name, "hpx-photon-usercq") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_photon_usercq_arg), 
                 &(args_info->hpx_photon_usercq_orig), &(args_info->hpx_photon_usercq_given),
                &(local_args_info.hpx_photon_usercq_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-photon-usercq", '-',
                additional_error))
              goto failure;
          
          }
          /* optimize for SMP execution.  */
          else if (strcmp (long_options[option_index].name, "hpx-opt-smp") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_opt_smp_arg), 
                 &(args_info->hpx_opt_smp_orig), &(args_info->hpx_opt_smp_given),
                &(local_args_info.hpx_opt_smp_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-opt-smp", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", HPX_OPTION_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->hpx_log_at_arg),
    &(args_info->hpx_log_at_orig), args_info->hpx_log_at_given,
    local_args_info.hpx_log_at_given, 0,
    ARG_INT, hpx_log_at_list);
  multiple_default_value.int_arg = hpx_log_level_arg_all;
  update_multiple_arg((void *)&(args_info->hpx_log_level_arg),
    &(args_info->hpx_log_level_orig), args_info->hpx_log_level_given,
    local_args_info.hpx_log_level_given, &multiple_default_value,
    ARG_ENUM, hpx_log_level_list);
  update_multiple_arg((void *)&(args_info->hpx_dbg_waitat_arg),
    &(args_info->hpx_dbg_waitat_orig), args_info->hpx_dbg_waitat_given,
    local_args_info.hpx_dbg_waitat_given, 0,
    ARG_INT, hpx_dbg_waitat_list);
  multiple_default_value.int_arg = hpx_dbg_waitonsig_arg_all;
  update_multiple_arg((void *)&(args_info->hpx_dbg_waitonsig_arg),
    &(args_info->hpx_dbg_waitonsig_orig), args_info->hpx_dbg_waitonsig_given,
    local_args_info.hpx_dbg_waitonsig_given, &multiple_default_value,
    ARG_ENUM, hpx_dbg_waitonsig_list);
  update_multiple_arg((void *)&(args_info->hpx_inst_at_arg),
    &(args_info->hpx_inst_at_orig), args_info->hpx_inst_at_given,
    local_args_info.hpx_inst_at_given, 0,
    ARG_INT, hpx_inst_at_list);
  update_multiple_arg((void *)&(args_info->hpx_trace_classes_arg),
    &(args_info->hpx_trace_classes_orig), args_info->hpx_trace_classes_given,
    local_args_info.hpx_trace_classes_given, 0,
    ARG_ENUM, hpx_trace_classes_list);
  update_multiple_arg((void *)&(args_info->hpx_prof_counters_arg),
    &(args_info->hpx_prof_counters_orig), args_info->hpx_prof_counters_given,
    local_args_info.hpx_prof_counters_given, 0,
    ARG_ENUM, hpx_prof_counters_list);

  args_info->hpx_log_at_given += local_args_info.hpx_log_at_given;
  local_args_info.hpx_log_at_given = 0;
  args_info->hpx_log_level_given += local_args_info.hpx_log_level_given;
  local_args_info.hpx_log_level_given = 0;
  args_info->hpx_dbg_waitat_given += local_args_info.hpx_dbg_waitat_given;
  local_args_info.hpx_dbg_waitat_given = 0;
  args_info->hpx_dbg_waitonsig_given += local_args_info.hpx_dbg_waitonsig_given;
  local_args_info.hpx_dbg_waitonsig_given = 0;
  args_info->hpx_inst_at_given += local_args_info.hpx_inst_at_given;
  local_args_info.hpx_inst_at_given = 0;
  args_info->hpx_trace_classes_given += local_args_info.hpx_trace_classes_given;
  local_args_info.hpx_trace_classes_given = 0;
  args_info->hpx_prof_counters_given += local_args_info.hpx_prof_counters_given;
  local_args_info.hpx_prof_counters_given = 0;
  
  if (check_required)
    {
      error_occurred += hpx_option_parser_required2 (args_info, argv[0], additional_error);
    }

  hpx_option_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (hpx_log_at_list, 0 );
  free_list (hpx_log_level_list, 0 );
  free_list (hpx_dbg_waitat_list, 0 );
  free_list (hpx_dbg_waitonsig_list, 0 );
  free_list (hpx_inst_at_list, 0 );
  free_list (hpx_trace_classes_list, 0 );
  free_list (hpx_prof_counters_list, 0 );
  
  hpx_option_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

#ifndef CONFIG_FILE_LINE_SIZE
#define CONFIG_FILE_LINE_SIZE 2048
#endif
#define ADDITIONAL_ERROR " in configuration file "

#define CONFIG_FILE_LINE_BUFFER_SIZE (CONFIG_FILE_LINE_SIZE+3)
/* 3 is for "--" and "=" */

static int
_hpx_option_parser_configfile (const char *filename, int *my_argc)
{
  FILE* file;
  char my_argv[CONFIG_FILE_LINE_BUFFER_SIZE+1];
  char linebuf[CONFIG_FILE_LINE_SIZE];
  int line_num = 0;
  int result = 0, equal;
  char *fopt, *farg;
  char *str_index;
  size_t len, next_token;
  char delimiter;

  if ((file = fopen(filename, "r")) == 0)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               HPX_OPTION_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  while ((fgets(linebuf, CONFIG_FILE_LINE_SIZE, file)) != 0)
    {
      ++line_num;
      my_argv[0] = '\0';
      len = strlen(linebuf);
      if (len > (CONFIG_FILE_LINE_BUFFER_SIZE-1))
        {
          fprintf (stderr, "%s:%s:%d: Line too long in configuration file\n",
                   HPX_OPTION_PARSER_PACKAGE, filename, line_num);
          result = EXIT_FAILURE;
          break;
        }

      /* find first non-whitespace character in the line */
      next_token = strspn (linebuf, " \t\r\n");
      str_index  = linebuf + next_token;

      if ( str_index[0] == '\0' || str_index[0] == '#')
        continue; /* empty line or comment line is skipped */

      fopt = str_index;

      /* truncate fopt at the end of the first non-valid character */
      next_token = strcspn (fopt, " \t\r\n=");

      if (fopt[next_token] == '\0') /* the line is over */
        {
          farg  = 0;
          equal = 0;
          goto noarg;
        }

      /* remember if equal sign is present */
      equal = (fopt[next_token] == '=');
      fopt[next_token++] = '\0';

      /* advance pointers to the next token after the end of fopt */
      next_token += strspn (fopt + next_token, " \t\r\n");

      /* check for the presence of equal sign, and if so, skip it */
      if ( !equal )
        if ((equal = (fopt[next_token] == '=')))
          {
            next_token++;
            next_token += strspn (fopt + next_token, " \t\r\n");
          }
      str_index  += next_token;

      /* find argument */
      farg = str_index;
      if ( farg[0] == '\"' || farg[0] == '\'' )
        { /* quoted argument */
          str_index = strchr (++farg, str_index[0] ); /* skip opening quote */
          if (! str_index)
            {
              fprintf
                (stderr,
                 "%s:%s:%d: unterminated string in configuration file\n",
                 HPX_OPTION_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }
      else
        { /* read up the remaining part up to a delimiter */
          next_token = strcspn (farg, " \t\r\n#\'\"");
          str_index += next_token;
        }

      /* truncate farg at the delimiter and store it for further check */
      delimiter = *str_index, *str_index++ = '\0';

      /* everything but comment is illegal at the end of line */
      if (delimiter != '\0' && delimiter != '#')
        {
          str_index += strspn(str_index, " \t\r\n");
          if (*str_index != '\0' && *str_index != '#')
            {
              fprintf
                (stderr,
                 "%s:%s:%d: malformed string in configuration file\n",
                 HPX_OPTION_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }

    noarg:
      if (!strcmp(fopt,"include")) {
        if (farg && *farg) {
          result = _hpx_option_parser_configfile(farg, my_argc);
        } else {
          fprintf(stderr, "%s:%s:%d: include requires a filename argument.\n",
                  HPX_OPTION_PARSER_PACKAGE, filename, line_num);
        }
        continue;
      }
      len = strlen(fopt);
      strcat (my_argv, len > 1 ? "--" : "-");
      strcat (my_argv, fopt);
      if (len > 1 && ((farg && *farg) || equal))
        strcat (my_argv, "=");
      if (farg && *farg)
        strcat (my_argv, farg);
      ++(*my_argc);

      cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
      cmd_line_list_tmp->next = cmd_line_list;
      cmd_line_list = cmd_line_list_tmp;
      cmd_line_list->string_arg = gengetopt_strdup(my_argv);
    } /* while */

  if (file)
    fclose(file);
  return result;
}

int
hpx_option_parser_configfile (
  const char *filename,
                           struct hpx_options_t *args_info,
                           int override, int initialize, int check_required)
{
  struct hpx_option_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;
  
  return hpx_option_parser_config_file (filename, args_info, &params);
}

int
hpx_option_parser_config_file (const char *filename,
                           struct hpx_options_t *args_info,
                           struct hpx_option_parser_params *params)
{
  int i, result;
  int my_argc = 1;
  char **my_argv_arg;
  char *additional_error;

  /* store the program name */
  cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
  cmd_line_list_tmp->next = cmd_line_list;
  cmd_line_list = cmd_line_list_tmp;
  cmd_line_list->string_arg = gengetopt_strdup (HPX_OPTION_PARSER_PACKAGE);

  result = _hpx_option_parser_configfile(filename, &my_argc);

  if (result != EXIT_FAILURE) {
    my_argv_arg = (char **) malloc((my_argc+1) * sizeof(char *));
    cmd_line_list_tmp = cmd_line_list;

    for (i = my_argc - 1; i >= 0; --i) {
      my_argv_arg[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

    my_argv_arg[my_argc] = 0;

    additional_error = (char *)malloc(strlen(filename) + strlen(ADDITIONAL_ERROR) + 1);
    strcpy (additional_error, ADDITIONAL_ERROR);
    strcat (additional_error, filename);
    result =
      hpx_option_parser_internal (my_argc, my_argv_arg, args_info,
                              params,
                              additional_error);

    free (additional_error);
    free (my_argv_arg);
  }

  free_cmd_list();
  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

static unsigned int
hpx_option_parser_create_argv(const char *cmdline_, char ***argv_ptr, const char *prog_name)
{
  char *cmdline, *p;
  size_t n = 0, j;
  int i;

  if (prog_name) {
    cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
    cmd_line_list_tmp->next = cmd_line_list;
    cmd_line_list = cmd_line_list_tmp;
    cmd_line_list->string_arg = gengetopt_strdup (prog_name);

    ++n;
  }

  cmdline = gengetopt_strdup(cmdline_);
  p = cmdline;

  while (p && strlen(p))
    {
      j = strcspn(p, " \t");
      ++n;
      if (j && j < strlen(p))
        {
          p[j] = '\0';

          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          p += (j+1);
          p += strspn(p, " \t");
        }
      else
        {
          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          break;
        }
    }

  *argv_ptr = (char **) malloc((n + 1) * sizeof(char *));
  cmd_line_list_tmp = cmd_line_list;
  for (i = (n-1); i >= 0; --i)
    {
      (*argv_ptr)[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

  (*argv_ptr)[n] = 0;

  free(cmdline);
  return n;
}

int
hpx_option_parser_string(const char *cmdline, struct hpx_options_t *args_info, const char *prog_name)
{
  return hpx_option_parser_string2(cmdline, args_info, prog_name, 0, 1, 1);
}

int
hpx_option_parser_string2(const char *cmdline, struct hpx_options_t *args_info, const char *prog_name,
    int override, int initialize, int check_required)
{
  struct hpx_option_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  return hpx_option_parser_string_ext(cmdline, args_info, prog_name, &params);
}

int
hpx_option_parser_string_ext(const char *cmdline, struct hpx_options_t *args_info, const char *prog_name,
    struct hpx_option_parser_params *params)
{
  char **argv_ptr = 0;
  int result;
  unsigned int argc;
  
  argc = hpx_option_parser_create_argv(cmdline, &argv_ptr, prog_name);
  
  result =
    hpx_option_parser_internal (argc, argv_ptr, args_info, params, 0);
  
  if (argv_ptr)
    {
      free (argv_ptr);
    }

  free_cmd_list();
  
  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

