/*
  File autogenerated by gengetopt version 2.22
  generated with the following command:
  gengetopt --input=options.ggo --func-name=hpx_option_parser --arg-struct-name=hpx_options_t --file-name=parser --default-optional --string-parser --conf-parser --no-help --no-version

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "parser.h"

const char *hpx_options_t_purpose = "";

const char *hpx_options_t_usage = "Usage: " HPX_OPTION_PARSER_PACKAGE " [OPTIONS]...";

const char *hpx_options_t_description = "";

const char *hpx_options_t_help[] = {
  "HPX Runtime Options:",
  "All of the following options can either be set through the\ncommand-line using the flags given below, or through environment\nvariables of the form HPX_OPTION=value, where the option corresponds\nto the flag suffix given below.",
  "      --hpx-cores=cores         number of cores to run on",
  "      --hpx-threads=threads     number of scheduler threads",
  "      --hpx-backoffmax=count    upper bound for worker-thread backoff",
  "      --hpx-stacksize=bytes     set HPX stack size",
  "      --hpx-heapsize=bytes      set HPX per-PE global heap size",
  "      --hpx-gas=type            type of Global Address Space (GAS)  (possible \n                                  values=\"default\", \"smp\", \"pgas\", \n                                  \"agas\", \"pgas_switch\", \"agas_switch\")",
  "      --hpx-boot=type           HPX bootstrap method to use  (possible \n                                  values=\"default\", \"smp\", \"mpi\", \n                                  \"pmi\")",
  "      --hpx-transport=type      type of transport to use  (possible \n                                  values=\"default\", \"smp\", \"mpi\", \n                                  \"portals\", \"photon\")",
  "      --hpx-network=type        type of network to use  (possible \n                                  values=\"default\", \"smp\", \"pwc\", \n                                  \"isir\")",
  "      --hpx-waitat[=locality]   wait for debugger at specific locality",
  "      --hpx-loglevel[=level]    set the logging level  (possible \n                                  values=\"default\", \"boot\", \"sched\", \n                                  \"gas\", \"lco\", \"net\", \"trans\", \n                                  \"parcel\", \"all\")",
  "      --hpx-logat=[localities]  selectively output log information",
  "      --hpx-statistics          print HPX runtime statistics  (default=off)",
  "      --hpx-sendlimit=requests  HPX transport-specific send limit",
  "      --hpx-recvlimit=requests  HPX transport-specific recv limit",
  "      --hpx-configfile=file     HPX runtime configuration file",
  "      --hpx-mprotectstacks      use mprotect() to bracket stacks to look for \n                                  stack overflows  (default=off)",
  "      --hpx-waitonabort         call hpx_wait() inside of hpx_abort() for \n                                  debugging  (default=off)",
  "\nPWC Network Options:",
  "      --hpx-parcelbuffersize=LONG\n                                set the size of p2p recv buffers for parcel \n                                  sends",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_LONG
  , ARG_ENUM
} hpx_option_parser_arg_type;

static
void clear_given (struct hpx_options_t *args_info);
static
void clear_args (struct hpx_options_t *args_info);

static int
hpx_option_parser_internal (int argc, char * const *argv, struct hpx_options_t *args_info,
                        struct hpx_option_parser_params *params, const char *additional_error);

static int
hpx_option_parser_required2 (struct hpx_options_t *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


char *hpx_option_parser_hpx_gas_values[] = {"default", "smp", "pgas", "agas", "pgas_switch", "agas_switch", 0} ;	/* Possible values for hpx-gas.  */
char *hpx_option_parser_hpx_boot_values[] = {"default", "smp", "mpi", "pmi", 0} ;	/* Possible values for hpx-boot.  */
char *hpx_option_parser_hpx_transport_values[] = {"default", "smp", "mpi", "portals", "photon", 0} ;	/* Possible values for hpx-transport.  */
char *hpx_option_parser_hpx_network_values[] = {"default", "smp", "pwc", "isir", 0} ;	/* Possible values for hpx-network.  */
char *hpx_option_parser_hpx_loglevel_values[] = {"default", "boot", "sched", "gas", "lco", "net", "trans", "parcel", "all", 0} ;	/* Possible values for hpx-loglevel.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct hpx_options_t *args_info)
{
  args_info->hpx_cores_given = 0 ;
  args_info->hpx_threads_given = 0 ;
  args_info->hpx_backoffmax_given = 0 ;
  args_info->hpx_stacksize_given = 0 ;
  args_info->hpx_heapsize_given = 0 ;
  args_info->hpx_gas_given = 0 ;
  args_info->hpx_boot_given = 0 ;
  args_info->hpx_transport_given = 0 ;
  args_info->hpx_network_given = 0 ;
  args_info->hpx_waitat_given = 0 ;
  args_info->hpx_loglevel_given = 0 ;
  args_info->hpx_logat_given = 0 ;
  args_info->hpx_statistics_given = 0 ;
  args_info->hpx_sendlimit_given = 0 ;
  args_info->hpx_recvlimit_given = 0 ;
  args_info->hpx_configfile_given = 0 ;
  args_info->hpx_mprotectstacks_given = 0 ;
  args_info->hpx_waitonabort_given = 0 ;
  args_info->hpx_parcelbuffersize_given = 0 ;
}

static
void clear_args (struct hpx_options_t *args_info)
{
  args_info->hpx_cores_orig = NULL;
  args_info->hpx_threads_orig = NULL;
  args_info->hpx_backoffmax_orig = NULL;
  args_info->hpx_stacksize_orig = NULL;
  args_info->hpx_heapsize_orig = NULL;
  args_info->hpx_gas_arg = -1;
  args_info->hpx_gas_orig = NULL;
  args_info->hpx_boot_arg = -1;
  args_info->hpx_boot_orig = NULL;
  args_info->hpx_transport_arg = -1;
  args_info->hpx_transport_orig = NULL;
  args_info->hpx_network_arg = -1;
  args_info->hpx_network_orig = NULL;
  args_info->hpx_waitat_arg = NULL;
  args_info->hpx_waitat_orig = NULL;
  args_info->hpx_loglevel_arg = NULL;
  args_info->hpx_loglevel_orig = NULL;
  args_info->hpx_logat_arg = NULL;
  args_info->hpx_logat_orig = NULL;
  args_info->hpx_statistics_flag = 0;
  args_info->hpx_sendlimit_orig = NULL;
  args_info->hpx_recvlimit_orig = NULL;
  args_info->hpx_configfile_arg = NULL;
  args_info->hpx_configfile_orig = NULL;
  args_info->hpx_mprotectstacks_flag = 0;
  args_info->hpx_waitonabort_flag = 0;
  args_info->hpx_parcelbuffersize_orig = NULL;
  
}

static
void init_args_info(struct hpx_options_t *args_info)
{


  args_info->hpx_cores_help = hpx_options_t_help[2] ;
  args_info->hpx_threads_help = hpx_options_t_help[3] ;
  args_info->hpx_backoffmax_help = hpx_options_t_help[4] ;
  args_info->hpx_stacksize_help = hpx_options_t_help[5] ;
  args_info->hpx_heapsize_help = hpx_options_t_help[6] ;
  args_info->hpx_gas_help = hpx_options_t_help[7] ;
  args_info->hpx_boot_help = hpx_options_t_help[8] ;
  args_info->hpx_transport_help = hpx_options_t_help[9] ;
  args_info->hpx_network_help = hpx_options_t_help[10] ;
  args_info->hpx_waitat_help = hpx_options_t_help[11] ;
  args_info->hpx_waitat_min = -1;
  args_info->hpx_waitat_max = -1;
  args_info->hpx_loglevel_help = hpx_options_t_help[12] ;
  args_info->hpx_loglevel_min = -1;
  args_info->hpx_loglevel_max = -1;
  args_info->hpx_logat_help = hpx_options_t_help[13] ;
  args_info->hpx_logat_min = -1;
  args_info->hpx_logat_max = -1;
  args_info->hpx_statistics_help = hpx_options_t_help[14] ;
  args_info->hpx_sendlimit_help = hpx_options_t_help[15] ;
  args_info->hpx_recvlimit_help = hpx_options_t_help[16] ;
  args_info->hpx_configfile_help = hpx_options_t_help[17] ;
  args_info->hpx_mprotectstacks_help = hpx_options_t_help[18] ;
  args_info->hpx_waitonabort_help = hpx_options_t_help[19] ;
  args_info->hpx_parcelbuffersize_help = hpx_options_t_help[21] ;
  
}

void
hpx_option_parser_print_version (void)
{
  printf ("%s %s\n", HPX_OPTION_PARSER_PACKAGE, HPX_OPTION_PARSER_VERSION);
}

static void print_help_common(void) {
  hpx_option_parser_print_version ();

  if (strlen(hpx_options_t_purpose) > 0)
    printf("\n%s\n", hpx_options_t_purpose);

  if (strlen(hpx_options_t_usage) > 0)
    printf("\n%s\n", hpx_options_t_usage);

  printf("\n");

  if (strlen(hpx_options_t_description) > 0)
    printf("%s\n", hpx_options_t_description);
}

void
hpx_option_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (hpx_options_t_help[i])
    printf("%s\n", hpx_options_t_help[i++]);
}

void
hpx_option_parser_init (struct hpx_options_t *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
hpx_option_parser_params_init(struct hpx_option_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct hpx_option_parser_params *
hpx_option_parser_params_create(void)
{
  struct hpx_option_parser_params *params = 
    (struct hpx_option_parser_params *)malloc(sizeof(struct hpx_option_parser_params));
  hpx_option_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    long long_arg;
    char *string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = NULL;
  new_node->orig = NULL;
}

static void
free_multiple_field(unsigned int len, void **arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}


static void
hpx_option_parser_release (struct hpx_options_t *args_info)
{

  free_string_field (&(args_info->hpx_cores_orig));
  free_string_field (&(args_info->hpx_threads_orig));
  free_string_field (&(args_info->hpx_backoffmax_orig));
  free_string_field (&(args_info->hpx_stacksize_orig));
  free_string_field (&(args_info->hpx_heapsize_orig));
  free_string_field (&(args_info->hpx_gas_orig));
  free_string_field (&(args_info->hpx_boot_orig));
  free_string_field (&(args_info->hpx_transport_orig));
  free_string_field (&(args_info->hpx_network_orig));
  free_multiple_field (args_info->hpx_waitat_given, (void **)&(args_info->hpx_waitat_arg), &(args_info->hpx_waitat_orig));
  free_multiple_field (args_info->hpx_loglevel_given, (void **)&(args_info->hpx_loglevel_arg), &(args_info->hpx_loglevel_orig));
  free_multiple_field (args_info->hpx_logat_given, (void **)&(args_info->hpx_logat_arg), &(args_info->hpx_logat_orig));
  free_string_field (&(args_info->hpx_sendlimit_orig));
  free_string_field (&(args_info->hpx_recvlimit_orig));
  free_string_field (&(args_info->hpx_configfile_arg));
  free_string_field (&(args_info->hpx_configfile_orig));
  free_string_field (&(args_info->hpx_parcelbuffersize_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
hpx_option_parser_dump(FILE *outfile, struct hpx_options_t *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", HPX_OPTION_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->hpx_cores_given)
    write_into_file(outfile, "hpx-cores", args_info->hpx_cores_orig, 0);
  if (args_info->hpx_threads_given)
    write_into_file(outfile, "hpx-threads", args_info->hpx_threads_orig, 0);
  if (args_info->hpx_backoffmax_given)
    write_into_file(outfile, "hpx-backoffmax", args_info->hpx_backoffmax_orig, 0);
  if (args_info->hpx_stacksize_given)
    write_into_file(outfile, "hpx-stacksize", args_info->hpx_stacksize_orig, 0);
  if (args_info->hpx_heapsize_given)
    write_into_file(outfile, "hpx-heapsize", args_info->hpx_heapsize_orig, 0);
  if (args_info->hpx_gas_given)
    write_into_file(outfile, "hpx-gas", args_info->hpx_gas_orig, hpx_option_parser_hpx_gas_values);
  if (args_info->hpx_boot_given)
    write_into_file(outfile, "hpx-boot", args_info->hpx_boot_orig, hpx_option_parser_hpx_boot_values);
  if (args_info->hpx_transport_given)
    write_into_file(outfile, "hpx-transport", args_info->hpx_transport_orig, hpx_option_parser_hpx_transport_values);
  if (args_info->hpx_network_given)
    write_into_file(outfile, "hpx-network", args_info->hpx_network_orig, hpx_option_parser_hpx_network_values);
  write_multiple_into_file(outfile, args_info->hpx_waitat_given, "hpx-waitat", args_info->hpx_waitat_orig, 0);
  write_multiple_into_file(outfile, args_info->hpx_loglevel_given, "hpx-loglevel", args_info->hpx_loglevel_orig, hpx_option_parser_hpx_loglevel_values);
  write_multiple_into_file(outfile, args_info->hpx_logat_given, "hpx-logat", args_info->hpx_logat_orig, 0);
  if (args_info->hpx_statistics_given)
    write_into_file(outfile, "hpx-statistics", 0, 0 );
  if (args_info->hpx_sendlimit_given)
    write_into_file(outfile, "hpx-sendlimit", args_info->hpx_sendlimit_orig, 0);
  if (args_info->hpx_recvlimit_given)
    write_into_file(outfile, "hpx-recvlimit", args_info->hpx_recvlimit_orig, 0);
  if (args_info->hpx_configfile_given)
    write_into_file(outfile, "hpx-configfile", args_info->hpx_configfile_orig, 0);
  if (args_info->hpx_mprotectstacks_given)
    write_into_file(outfile, "hpx-mprotectstacks", 0, 0 );
  if (args_info->hpx_waitonabort_given)
    write_into_file(outfile, "hpx-waitonabort", 0, 0 );
  if (args_info->hpx_parcelbuffersize_given)
    write_into_file(outfile, "hpx-parcelbuffersize", args_info->hpx_parcelbuffersize_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
hpx_option_parser_file_save(const char *filename, struct hpx_options_t *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", HPX_OPTION_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = hpx_option_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
hpx_option_parser_free (struct hpx_options_t *args_info)
{
  hpx_option_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  char *tok, *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static char *
get_multiple_arg_token_next(const char *arg)
{
  char *tok;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc)
{
  int error = 0;

  if (option_given && ! (min < 0 && max < 0))
    {
      if (min >= 0 && max >= 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < min
              || option_given > max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min >= 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max >= 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
hpx_option_parser (int argc, char * const *argv, struct hpx_options_t *args_info)
{
  return hpx_option_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
hpx_option_parser_ext (int argc, char * const *argv, struct hpx_options_t *args_info,
                   struct hpx_option_parser_params *params)
{
  int result;
  result = hpx_option_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
hpx_option_parser2 (int argc, char * const *argv, struct hpx_options_t *args_info, int override, int initialize, int check_required)
{
  int result;
  struct hpx_option_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = hpx_option_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
hpx_option_parser_required (struct hpx_options_t *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (hpx_option_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
hpx_option_parser_required2 (struct hpx_options_t *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_waitat_given, args_info->hpx_waitat_min, args_info->hpx_waitat_max, "'--hpx-waitat'"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_loglevel_given, args_info->hpx_loglevel_min, args_info->hpx_loglevel_max, "'--hpx-loglevel'"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->hpx_logat_given, args_info->hpx_logat_min, args_info->hpx_logat_max, "'--hpx-logat'"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see hpx_option_parser_params.check_ambiguity
 * @param override @see hpx_option_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, char *possible_values[], const char *default_value,
               hpx_option_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_LONG:
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_LONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               char *possible_values[], const char *default_value,
               hpx_option_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *multi_token, *multi_next; /* store single arguments */

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               hpx_option_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
    case ARG_ENUM:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_LONG:
      *((long **)field) = (long *)realloc (*((long **)field), (field_given + prev_given) * sizeof (long)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_LONG:
          (*((long **)field))[i + field_given] = tmp->arg.long_arg; break;
        case ARG_ENUM:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
      case ARG_ENUM:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_LONG:
        if (! *((long **)field)) {
          *((long **)field) = (long *)malloc (sizeof (long));
          (*((long **)field))[0] = default_value->long_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = NULL;
      }
    }
  }
}

int
hpx_option_parser_internal (int argc, char * const *argv, struct hpx_options_t *args_info,
                        struct hpx_option_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * hpx_waitat_list = NULL;
  struct generic_list * hpx_loglevel_list = NULL;
  struct generic_list * hpx_logat_list = NULL;
  int error = 0;
  struct hpx_options_t local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    hpx_option_parser_init (args_info);

  hpx_option_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "hpx-cores",	1, NULL, 0 },
        { "hpx-threads",	1, NULL, 0 },
        { "hpx-backoffmax",	1, NULL, 0 },
        { "hpx-stacksize",	1, NULL, 0 },
        { "hpx-heapsize",	1, NULL, 0 },
        { "hpx-gas",	1, NULL, 0 },
        { "hpx-boot",	1, NULL, 0 },
        { "hpx-transport",	1, NULL, 0 },
        { "hpx-network",	1, NULL, 0 },
        { "hpx-waitat",	2, NULL, 0 },
        { "hpx-loglevel",	2, NULL, 0 },
        { "hpx-logat",	1, NULL, 0 },
        { "hpx-statistics",	0, NULL, 0 },
        { "hpx-sendlimit",	1, NULL, 0 },
        { "hpx-recvlimit",	1, NULL, 0 },
        { "hpx-configfile",	1, NULL, 0 },
        { "hpx-mprotectstacks",	0, NULL, 0 },
        { "hpx-waitonabort",	0, NULL, 0 },
        { "hpx-parcelbuffersize",	1, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {

        case 0:	/* Long option with no short option */
          /* number of cores to run on.  */
          if (strcmp (long_options[option_index].name, "hpx-cores") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_cores_arg), 
                 &(args_info->hpx_cores_orig), &(args_info->hpx_cores_given),
                &(local_args_info.hpx_cores_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-cores", '-',
                additional_error))
              goto failure;
          
          }
          /* number of scheduler threads.  */
          else if (strcmp (long_options[option_index].name, "hpx-threads") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_threads_arg), 
                 &(args_info->hpx_threads_orig), &(args_info->hpx_threads_given),
                &(local_args_info.hpx_threads_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-threads", '-',
                additional_error))
              goto failure;
          
          }
          /* upper bound for worker-thread backoff.  */
          else if (strcmp (long_options[option_index].name, "hpx-backoffmax") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_backoffmax_arg), 
                 &(args_info->hpx_backoffmax_orig), &(args_info->hpx_backoffmax_given),
                &(local_args_info.hpx_backoffmax_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "hpx-backoffmax", '-',
                additional_error))
              goto failure;
          
          }
          /* set HPX stack size.  */
          else if (strcmp (long_options[option_index].name, "hpx-stacksize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_stacksize_arg), 
                 &(args_info->hpx_stacksize_orig), &(args_info->hpx_stacksize_given),
                &(local_args_info.hpx_stacksize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-stacksize", '-',
                additional_error))
              goto failure;
          
          }
          /* set HPX per-PE global heap size.  */
          else if (strcmp (long_options[option_index].name, "hpx-heapsize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_heapsize_arg), 
                 &(args_info->hpx_heapsize_orig), &(args_info->hpx_heapsize_given),
                &(local_args_info.hpx_heapsize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-heapsize", '-',
                additional_error))
              goto failure;
          
          }
          /* type of Global Address Space (GAS).  */
          else if (strcmp (long_options[option_index].name, "hpx-gas") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_gas_arg), 
                 &(args_info->hpx_gas_orig), &(args_info->hpx_gas_given),
                &(local_args_info.hpx_gas_given), optarg, hpx_option_parser_hpx_gas_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-gas", '-',
                additional_error))
              goto failure;
          
          }
          /* HPX bootstrap method to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-boot") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_boot_arg), 
                 &(args_info->hpx_boot_orig), &(args_info->hpx_boot_given),
                &(local_args_info.hpx_boot_given), optarg, hpx_option_parser_hpx_boot_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-boot", '-',
                additional_error))
              goto failure;
          
          }
          /* type of transport to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-transport") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_transport_arg), 
                 &(args_info->hpx_transport_orig), &(args_info->hpx_transport_given),
                &(local_args_info.hpx_transport_given), optarg, hpx_option_parser_hpx_transport_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-transport", '-',
                additional_error))
              goto failure;
          
          }
          /* type of network to use.  */
          else if (strcmp (long_options[option_index].name, "hpx-network") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_network_arg), 
                 &(args_info->hpx_network_orig), &(args_info->hpx_network_given),
                &(local_args_info.hpx_network_given), optarg, hpx_option_parser_hpx_network_values, 0, ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "hpx-network", '-',
                additional_error))
              goto failure;
          
          }
          /* wait for debugger at specific locality.  */
          else if (strcmp (long_options[option_index].name, "hpx-waitat") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_waitat_list, 
                &(local_args_info.hpx_waitat_given), optarg, 0, 0, ARG_INT,
                "hpx-waitat", '-',
                additional_error))
              goto failure;
          
          }
          /* set the logging level.  */
          else if (strcmp (long_options[option_index].name, "hpx-loglevel") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_loglevel_list, 
                &(local_args_info.hpx_loglevel_given), optarg, hpx_option_parser_hpx_loglevel_values, 0, ARG_ENUM,
                "hpx-loglevel", '-',
                additional_error))
              goto failure;
          
          }
          /* selectively output log information.  */
          else if (strcmp (long_options[option_index].name, "hpx-logat") == 0)
          {
          
            if (update_multiple_arg_temp(&hpx_logat_list, 
                &(local_args_info.hpx_logat_given), optarg, 0, 0, ARG_INT,
                "hpx-logat", '-',
                additional_error))
              goto failure;
          
          }
          /* print HPX runtime statistics.  */
          else if (strcmp (long_options[option_index].name, "hpx-statistics") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_statistics_flag), 0, &(args_info->hpx_statistics_given),
                &(local_args_info.hpx_statistics_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-statistics", '-',
                additional_error))
              goto failure;
          
          }
          /* HPX transport-specific send limit.  */
          else if (strcmp (long_options[option_index].name, "hpx-sendlimit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_sendlimit_arg), 
                 &(args_info->hpx_sendlimit_orig), &(args_info->hpx_sendlimit_given),
                &(local_args_info.hpx_sendlimit_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-sendlimit", '-',
                additional_error))
              goto failure;
          
          }
          /* HPX transport-specific recv limit.  */
          else if (strcmp (long_options[option_index].name, "hpx-recvlimit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_recvlimit_arg), 
                 &(args_info->hpx_recvlimit_orig), &(args_info->hpx_recvlimit_given),
                &(local_args_info.hpx_recvlimit_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-recvlimit", '-',
                additional_error))
              goto failure;
          
          }
          /* HPX runtime configuration file.  */
          else if (strcmp (long_options[option_index].name, "hpx-configfile") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_configfile_arg), 
                 &(args_info->hpx_configfile_orig), &(args_info->hpx_configfile_given),
                &(local_args_info.hpx_configfile_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "hpx-configfile", '-',
                additional_error))
              goto failure;
          
          }
          /* use mprotect() to bracket stacks to look for stack overflows.  */
          else if (strcmp (long_options[option_index].name, "hpx-mprotectstacks") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_mprotectstacks_flag), 0, &(args_info->hpx_mprotectstacks_given),
                &(local_args_info.hpx_mprotectstacks_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-mprotectstacks", '-',
                additional_error))
              goto failure;
          
          }
          /* call hpx_wait() inside of hpx_abort() for debugging.  */
          else if (strcmp (long_options[option_index].name, "hpx-waitonabort") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hpx_waitonabort_flag), 0, &(args_info->hpx_waitonabort_given),
                &(local_args_info.hpx_waitonabort_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hpx-waitonabort", '-',
                additional_error))
              goto failure;
          
          }
          /* set the size of p2p recv buffers for parcel sends.  */
          else if (strcmp (long_options[option_index].name, "hpx-parcelbuffersize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hpx_parcelbuffersize_arg), 
                 &(args_info->hpx_parcelbuffersize_orig), &(args_info->hpx_parcelbuffersize_given),
                &(local_args_info.hpx_parcelbuffersize_given), optarg, 0, 0, ARG_LONG,
                check_ambiguity, override, 0, 0,
                "hpx-parcelbuffersize", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", HPX_OPTION_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->hpx_waitat_arg),
    &(args_info->hpx_waitat_orig), args_info->hpx_waitat_given,
    local_args_info.hpx_waitat_given, 0 , 
    ARG_INT, hpx_waitat_list);
  update_multiple_arg((void *)&(args_info->hpx_loglevel_arg),
    &(args_info->hpx_loglevel_orig), args_info->hpx_loglevel_given,
    local_args_info.hpx_loglevel_given, 0 , 
    ARG_ENUM, hpx_loglevel_list);
  update_multiple_arg((void *)&(args_info->hpx_logat_arg),
    &(args_info->hpx_logat_orig), args_info->hpx_logat_given,
    local_args_info.hpx_logat_given, 0 , 
    ARG_INT, hpx_logat_list);

  args_info->hpx_waitat_given += local_args_info.hpx_waitat_given;
  local_args_info.hpx_waitat_given = 0;
  args_info->hpx_loglevel_given += local_args_info.hpx_loglevel_given;
  local_args_info.hpx_loglevel_given = 0;
  args_info->hpx_logat_given += local_args_info.hpx_logat_given;
  local_args_info.hpx_logat_given = 0;
  
  if (check_required)
    {
      error += hpx_option_parser_required2 (args_info, argv[0], additional_error);
    }

  hpx_option_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (hpx_waitat_list, 0 );
  free_list (hpx_loglevel_list, 0 );
  free_list (hpx_logat_list, 0 );
  
  hpx_option_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

#ifndef CONFIG_FILE_LINE_SIZE
#define CONFIG_FILE_LINE_SIZE 2048
#endif
#define ADDITIONAL_ERROR " in configuration file "

#define CONFIG_FILE_LINE_BUFFER_SIZE (CONFIG_FILE_LINE_SIZE+3)
/* 3 is for "--" and "=" */

static int
_hpx_option_parser_configfile (char * const filename, int *my_argc)
{
  FILE* file;
  char my_argv[CONFIG_FILE_LINE_BUFFER_SIZE+1];
  char linebuf[CONFIG_FILE_LINE_SIZE];
  int line_num = 0;
  int result = 0, equal;
  char *fopt, *farg;
  char *str_index;
  size_t len, next_token;
  char delimiter;

  if ((file = fopen(filename, "r")) == NULL)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               HPX_OPTION_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  while ((fgets(linebuf, CONFIG_FILE_LINE_SIZE, file)) != NULL)
    {
      ++line_num;
      my_argv[0] = '\0';
      len = strlen(linebuf);
      if (len > (CONFIG_FILE_LINE_BUFFER_SIZE-1))
        {
          fprintf (stderr, "%s:%s:%d: Line too long in configuration file\n",
                   HPX_OPTION_PARSER_PACKAGE, filename, line_num);
          result = EXIT_FAILURE;
          break;
        }

      /* find first non-whitespace character in the line */
      next_token = strspn (linebuf, " \t\r\n");
      str_index  = linebuf + next_token;

      if ( str_index[0] == '\0' || str_index[0] == '#')
        continue; /* empty line or comment line is skipped */

      fopt = str_index;

      /* truncate fopt at the end of the first non-valid character */
      next_token = strcspn (fopt, " \t\r\n=");

      if (fopt[next_token] == '\0') /* the line is over */
        {
          farg  = NULL;
          equal = 0;
          goto noarg;
        }

      /* remember if equal sign is present */
      equal = (fopt[next_token] == '=');
      fopt[next_token++] = '\0';

      /* advance pointers to the next token after the end of fopt */
      next_token += strspn (fopt + next_token, " \t\r\n");

      /* check for the presence of equal sign, and if so, skip it */
      if ( !equal )
        if ((equal = (fopt[next_token] == '=')))
          {
            next_token++;
            next_token += strspn (fopt + next_token, " \t\r\n");
          }
      str_index  += next_token;

      /* find argument */
      farg = str_index;
      if ( farg[0] == '\"' || farg[0] == '\'' )
        { /* quoted argument */
          str_index = strchr (++farg, str_index[0] ); /* skip opening quote */
          if (! str_index)
            {
              fprintf
                (stderr,
                 "%s:%s:%d: unterminated string in configuration file\n",
                 HPX_OPTION_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }
      else
        { /* read up the remaining part up to a delimiter */
          next_token = strcspn (farg, " \t\r\n#\'\"");
          str_index += next_token;
        }

      /* truncate farg at the delimiter and store it for further check */
      delimiter = *str_index, *str_index++ = '\0';

      /* everything but comment is illegal at the end of line */
      if (delimiter != '\0' && delimiter != '#')
        {
          str_index += strspn(str_index, " \t\r\n");
          if (*str_index != '\0' && *str_index != '#')
            {
              fprintf
                (stderr,
                 "%s:%s:%d: malformed string in configuration file\n",
                 HPX_OPTION_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }

    noarg:
      if (!strcmp(fopt,"include")) {
        if (farg && *farg) {
          result = _hpx_option_parser_configfile(farg, my_argc);
        } else {
          fprintf(stderr, "%s:%s:%d: include requires a filename argument.\n",
                  HPX_OPTION_PARSER_PACKAGE, filename, line_num);
        }
        continue;
      }
      len = strlen(fopt);
      strcat (my_argv, len > 1 ? "--" : "-");
      strcat (my_argv, fopt);
      if (len > 1 && ((farg && *farg) || equal))
        strcat (my_argv, "=");
      if (farg && *farg)
        strcat (my_argv, farg);
      ++(*my_argc);

      cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
      cmd_line_list_tmp->next = cmd_line_list;
      cmd_line_list = cmd_line_list_tmp;
      cmd_line_list->string_arg = gengetopt_strdup(my_argv);
    } /* while */

  if (file)
    fclose(file);
  return result;
}

int
hpx_option_parser_configfile (char * const filename,
                           struct hpx_options_t *args_info,
                           int override, int initialize, int check_required)
{
  struct hpx_option_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;
  
  return hpx_option_parser_config_file (filename, args_info, &params);
}

int
hpx_option_parser_config_file (char * const filename,
                           struct hpx_options_t *args_info,
                           struct hpx_option_parser_params *params)
{
  int i, result;
  int my_argc = 1;
  char **my_argv_arg;
  char *additional_error;

  /* store the program name */
  cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
  cmd_line_list_tmp->next = cmd_line_list;
  cmd_line_list = cmd_line_list_tmp;
  cmd_line_list->string_arg = gengetopt_strdup (HPX_OPTION_PARSER_PACKAGE);

  result = _hpx_option_parser_configfile(filename, &my_argc);

  if (result != EXIT_FAILURE) {
    my_argv_arg = (char **) malloc((my_argc+1) * sizeof(char *));
    cmd_line_list_tmp = cmd_line_list;

    for (i = my_argc - 1; i >= 0; --i) {
      my_argv_arg[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

    my_argv_arg[my_argc] = 0;

    additional_error = (char *)malloc(strlen(filename) + strlen(ADDITIONAL_ERROR) + 1);
    strcpy (additional_error, ADDITIONAL_ERROR);
    strcat (additional_error, filename);
    result =
      hpx_option_parser_internal (my_argc, my_argv_arg, args_info,
                              params,
                              additional_error);

    free (additional_error);
    free (my_argv_arg);
  }

  free_cmd_list();
  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

static unsigned int
hpx_option_parser_create_argv(const char *cmdline_, char ***argv_ptr, const char *prog_name)
{
  char *cmdline, *p;
  size_t n = 0, j;
  int i;

  if (prog_name) {
    cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
    cmd_line_list_tmp->next = cmd_line_list;
    cmd_line_list = cmd_line_list_tmp;
    cmd_line_list->string_arg = gengetopt_strdup (prog_name);

    ++n;
  }

  cmdline = gengetopt_strdup(cmdline_);
  p = cmdline;

  while (p && strlen(p))
    {
      j = strcspn(p, " \t");
      ++n;
      if (j && j < strlen(p))
        {
          p[j] = '\0';

          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          p += (j+1);
          p += strspn(p, " \t");
        }
      else
        {
          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          break;
        }
    }

  *argv_ptr = (char **) malloc((n + 1) * sizeof(char *));
  cmd_line_list_tmp = cmd_line_list;
  for (i = (n-1); i >= 0; --i)
    {
      (*argv_ptr)[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

  (*argv_ptr)[n] = NULL;

  free(cmdline);
  return n;
}

int
hpx_option_parser_string(const char *cmdline, struct hpx_options_t *args_info, const char *prog_name)
{
  return hpx_option_parser_string2(cmdline, args_info, prog_name, 0, 1, 1);
}

int
hpx_option_parser_string2(const char *cmdline, struct hpx_options_t *args_info, const char *prog_name,
    int override, int initialize, int check_required)
{
  struct hpx_option_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  return hpx_option_parser_string_ext(cmdline, args_info, prog_name, &params);
}

int
hpx_option_parser_string_ext(const char *cmdline, struct hpx_options_t *args_info, const char *prog_name,
    struct hpx_option_parser_params *params)
{
  char **argv_ptr = 0;
  int result;
  unsigned int argc;
  
  argc = hpx_option_parser_create_argv(cmdline, &argv_ptr, prog_name);
  
  result =
    hpx_option_parser_internal (argc, argv_ptr, args_info, params, 0);
  
  if (argv_ptr)
    {
      free (argv_ptr);
    }

  free_cmd_list();
  
  if (result == EXIT_FAILURE)
    {
      hpx_option_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

